### ISSUE TITLE
Addon by default changes UI scaling

### ISSUE THREAD

**Issue by strayge** [drcika/apc-extension#1]
Just enabling addon changes scaling of file tree, activity bar, status bar, tab bar.

No addon settings specified.

Is there any option to disable UI changes until it explicitly turned on by user?

<details>
<summary>vscode version</summary>

```
Version: 1.79.0-insider (Universal)
Commit: 2dfb838f494f035099e999f0cd0eff5f1f488a30
Date: 2023-05-26T05:24:15.292Z
Electron: 22.5.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.6.0
```
</details>

### Expected behaviour

No style changes, until user explicitly enable options / set styles in settings.

### Actual behaviour

Font size and some icons became smaller in the next areas:
- file tree
- activity bar
- status bar
- tab bar

### After "Disable Apc extension" command

![image](https://github.com/drcika/apc-extension/assets/2664578/fc34d62f-c8af-47f9-9d4f-2a449215d9da)

### After "Enable Apc extension" command

![image](https://github.com/drcika/apc-extension/assets/2664578/cf0664d8-7263-4b09-af15-12dcc928ddff)

## Steps to reproduce

1. Install addon
2. Run "Enable Apc extension" command
3. Restart vscode

**Comment by mon-jai** [comment]
Agree that UI changes should be disabled by default.

Seems that they would be fixed by next release: https://github.com/iocave/customize-ui/issues/156#issuecomment-1566146830

**Comment by strayge** [comment]
Partial fix for me: in `modules/patch.js` change 
1. all `browser.getZoomFactor()` to `1`
2. default size in `activityBarConfig` from `35` to `48`

Now it close to original
![image](https://github.com/drcika/apc-extension/assets/2664578/ae180344-bcc4-4287-9f19-e4f577a99665)

But is still different from default styles:
- lower spacing around tab names
- bigger activity bar icons (with the same activity bar width)


P.S. I have `"window.zoomLevel": -1` in my config, probably scaling issue mostly coerced by it.
