### ISSUE TITLE
Unexpected behavior when sidebar is hidden.

### ISSUE THREAD

**Issue by markakritas** [drcika/apc-extension#10]
When toggling left sidebar off, status bar goes to the top hiding editor and right sidebar.

Sidebar not hidden view:

<img width="1492" alt="image" src="https://github.com/drcika/apc-extension/assets/40570077/5e8dcc84-c7e2-4419-b6a1-2c50908c2733">

Sidebar hidden view:

<img width="1492" alt="image" src="https://github.com/drcika/apc-extension/assets/40570077/cddd35c4-41e0-48c9-886c-c464eb3a03ae">

**Comment by nodgear** [comment]
![image](https://github.com/drcika/apc-extension/assets/22383863/9326f44f-2562-47c6-a34c-bf2227780c08)
Same here.

**Comment by drcika** [comment]
first part is solved,
there will be an update soon,
I don't understand the last problem

please don't use multiple extensions that do the same thing
in the next update it will be possible to import css/js

**Comment by markakritas** [comment]
> first part is solved, there will be an update soon, I don't understand the last problem
> 
> please don't use multiple extensions that do the same thing in the next update it will be possible to import css/js

I agree, no need for 2 extensions doing same things, but it was working along with `Custom CSS and JS Loader` without problem before last update. Also there are other extensions dependent on the mentioned extension.

**Comment by nodgear** [comment]
> first part is solved, there will be an update soon, I don't understand the last problem
> 
> please don't use multiple extensions that do the same thing in the next update it will be possible to import css/js

Understood, but my installation is fresh besides the color/icon theme. 
My last screenshot lacks context (i uploaded a gif but github only used the first frame), 

in the gif i hid the sidebar and it made my the status bar cover the whole editor area.

**Comment by drcika** [comment]
it should be fixed in the last version.
if it's still a problem i need more details like your settings, vscode/ vscodium, win/mac etc
so I can reproduce the problem

**Comment by nodgear** [comment]
It has indeeded been fixed.
thank you very much for your work.
