### ISSUE TITLE
how to install? 

### ISSUE THREAD

**Issue by fisforfaheem** [drcika/apc-extension#101]
no link or extension given

**Comment by ghost** [comment]
@fisforfaheem You can search `Apc Customize UI++` inside vscode `Extensions`

**Comment by backermanbd** [comment]
@drcika Could you add the extension marketplace link in the description?
https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension

**Comment by ghost** [comment]
@drcika Could you add this link in the website section of repository details?
https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension

To be more precise, here

![Capture](https://github.com/drcika/apc-extension/assets/84121715/3491f77d-63dc-45ab-93ac-f5307f261bbd)
