### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by h-jia** [drcika/apc-extension#102]
closed

**Comment by drcika** [comment]
originally there is no margin in that place,
explore other possible sources

or try
```
"apc.stylesheet": {
    ".terminal": "transform: translateY(-10px);"
}
```

**Comment by h-jia** [comment]
Thanks! Instead fixed by this:

```  
"apc.stylesheet": {
    ".basepanel .title": "height: 20px !important;",
    ".basepanel .title .monaco-action-bar": "height: 20px !important;",
    ".basepanel .title .title-actions": "height: 20px !important;",
  },
```

**Comment by ghost** [comment]
@h-jia Do you use the starship prompt?

If yes, then there's a workaround.

For .zshrc, use [this](https://www.reddit.com/r/commandline/comments/13r2ou3/comment/jli4rj1/?utm_source=share&utm_medium=web2x&context=3)
For .bashrc, use [this](https://www.reddit.com/r/commandline/comments/13r2ou3/comment/jliam5c/?utm_source=share&utm_medium=web2x&context=3)

**Comment by h-jia** [comment]
> @h-jia Do you use the starship prompt?
> 
> If yes, then there's a workaround.
> 
> For .zshrc, use [this](https://www.reddit.com/r/commandline/comments/13r2ou3/comment/jli4rj1/?utm_source=share&utm_medium=web2x&context=3) For .bashrc, use [this](https://www.reddit.com/r/commandline/comments/13r2ou3/comment/jliam5c/?utm_source=share&utm_medium=web2x&context=3)

Thank you! There's no issue for this:
<img width="434" alt="image" src="https://github.com/drcika/apc-extension/assets/29906369/7151ca7b-ca4b-418b-b24f-ccc57b355f32">


I fixed it (agressively) by using `"apc.stylesheet": {
    ".basepanel .title": "height: 0px !important;"}`
    
Thanks! Closed by fixed.
