### ISSUE TITLE
apc.imports not importing all css files

### ISSUE THREAD

**Issue by VincentBH** [drcika/apc-extension#105]
VSCode Version: 1.84.2

"apc.imports": [
  "/C:/VSCODE_CSS/A/style.css",
  "/C:/VSCODE_CSS/B/style.css",
  "/C:/VSCODE_CSS/C/style.css",
]

Only the last CSS file style is loaded, so in this case, C worked, but not AB. I can switch the order, but only the last works. 
Not sure if this is how it's meant to work, should I only be including one CSS and JS file for imports?

**Comment by markakritas** [comment]
I had same problem when started using extension, and merged all the css files into one.

**Comment by vdawg-git** [comment]
Same problem, this is a bug. 
I dont want to merge all CSS files though.

Is there a workaround for this?

I am on Arch Linux ( ${userHome} also does not work btw )
