### ISSUE TITLE
Hide keyboard shortcuts listed on the empty logo page

### ISSUE THREAD

**Issue by stephenhowells** [drcika/apc-extension#110]
Has anybody found a way to hide these?

<img width="400" alt="image" src="https://github.com/drcika/apc-extension/assets/436173/b4a6fec3-f0fa-4a11-af2d-2e42eb475e10">

**Comment by stephenhowells** [comment]
```css
"apc.stylesheet": {
    ".monaco-workbench .part.editor > .content .editor-group-container > .editor-group-watermark > .shortcuts dl": {
      "display": "none"
    }
}
```

**Comment by binaryben** [comment]
Does this do what you need in `settings.json`?

```
{
  "workbench.tips.enabled": false,
}
```

**Comment by ghost** [comment]
I don't get it. Instead of using default settings, why is everyone duct-taping all stuff?

**Comment by binaryben** [comment]
> I don't get it. Instead of using default settings, why is everyone duct-taping all stuff?

That's what happens when you give someone a hammer and forget to tell them to [RTFM first](https://code.visualstudio.com/docs/getstarted/settings#_default-settings). To be fair, APC is a very nice hammer and the settings.json file is very unwieldily if you don't know what you are looking for.

**Comment by ghost** [comment]
@binaryben Well said.

**Comment by stephenhowells** [comment]
> Does this do what you need in `settings.json`?
> 
> ```
> {
>   "workbench.tips.enabled": false,
> }
> ```

Thanks! I didn't know that was an option in the sea of VSCode settings.

**Comment by stephenhowells** [comment]
@binaryben 

> Does this do what you need in `settings.json`?
> 
> ```
> {
>   "workbench.tips.enabled": false,
> }
> ```

Thanks! I didn't know that was an option in the sea of VSCode settings.
