### ISSUE TITLE
Apc Customize UI++ is not working in the (VS Code) v1.85.1

### ISSUE THREAD

**Issue by MusabDev** [drcika/apc-extension#113]
Hello, 
When I woke up this morning, I noticed that my VS Code was updated. Unfortunately, the extension is not working. Can anyone share any workarounds or fixes?

Thanks!

**Comment by amnweb** [comment]
Open the Command Palette, type Enable Apc extension and restart VSCode.

**Comment by MusabDev** [comment]
It worked! Thank you! It's a bit weird because it's already enabled.
