### ISSUE TITLE
`apc.electron -> backgroundcolor` is ARGB instead of RGBA

### ISSUE THREAD

**Issue by LastExceed** [drcika/apc-extension#114]
hover text says RGBA, but `#FF800080` results in a fully opaque purple instead of half-transparent orange

**Comment by drcika** [comment]
RGBA => rgba(255, 255, 255, 1.0)
#FF800080 => Hex(ARGB)

https://www.electronjs.org/docs/latest/api/browser-window#winsetbackgroundcolorbackgroundcolor
