### ISSUE TITLE
Custom TItlebar with vibrancy

### ISSUE THREAD

**Issue by RoyalFoxy** [drcika/apc-extension#118]
I would like to know how I can have my titlebar also have the vibrancy applied but still being set to custom. I want it to be custom so I can still move around the window

Below is an image of what my vscode currently looks like, I use APC so I can have vibrancy and use vscode animations together.

<img width="2560" alt="image" src="https://github.com/drcika/apc-extension/assets/48829979/d9179b9e-adfd-43b1-a94d-c17d91d6a2bc">

If you know a way of moving the window with a native titlebar as well then please let me know!

**Comment by amnweb** [comment]
I’m not sure about macOS, but on Windows it’s not possible. This is an OS and electron limitation.
But you can set a `"titleBarStyle": "hiddenInset"`, adn than use a `trafficLightPosition`

**Comment by drcika** [comment]
unfortunately it seems that the titlebar cannot have vibrancy(I haven't found a way)
but you can still move the window without the title bar
```
"apc.electron": {
    ... other settings
    frame: fale 
    // or 
    "titleBarStyle": "hiddenInset",
}
```
