### ISSUE TITLE
Error with starting APC

### ISSUE THREAD

**Issue by k0st4dev** [drcika/apc-extension#122]
I get this error when trying to enable my APC extension
I'm on latest macOS, and latest VScode version

Apc Extension failed: Error: EROFS: read-only file system, rename '/private/var/folders/fx/gz6mr58n0tbb7nnwh3tt0b680000gn/T/AppTranslocation/F1CB893F-97F3-46BD-91E8-F063C5FC38C3/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/private/var/folders/fx/gz6mr58n0tbb7nnwh3tt0b680000gn/T/AppTranslocation/F1CB893F-97F3-46BD-91E8-F063C5FC38C3/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by k0st4dev** [comment]
I read it, and did sudo chown -R $(whoami) $(which code)

**Comment by drcika** [comment]
Probaj kroz terminal da instaliras vscode 
```
brew install --cask visual-studio-code
```

**Comment by k0st4dev** [comment]
jel mozes da mi napises komandu kako da obrisem ceo vscode i sve njegove fajlove prvo?

**Comment by drcika** [comment]
ne moras sve da brises samo ikonicu i aplication foldera prevuci u kantu

**Comment by drcika** [comment]
ako bas hoces sve
```
app
rm /Applications/Visual\ Studio\ Code

sav settings i cache
rm -rf ~/Library/Application\ Support/Code

sve ekstenzije
rm -rf  ~/.vscode
```

**Comment by k0st4dev** [comment]
instalirao sta sad

**Comment by drcika** [comment]
![Screenshot 2024-01-03 at 17 18 33](https://github.com/drcika/apc-extension/assets/35919606/9fe55fc7-e0f4-4f22-8ccb-ab1aa2adb656)

**Comment by k0st4dev** [comment]
Sad mi nije izasla greska

**Comment by drcika** [comment]
Po defultu nisi nista dobio
sve zavisi kako konfigurises 
otvori settings.json 
i dodaj sta hoces 

neki primer 
```
  "apc.electron": {
    "titleBarStyle": "hidden"
  },
  "apc.activityBar": {
    "position": "bottom"
  },
  "apc.statusBar": {
    "position": "top"
  },
  ```

**Comment by k0st4dev** [comment]
Vazi, hvala namestio sam sve
