### ISSUE TITLE
App Extension failed: EACCESS: Permission on Mac

### ISSUE THREAD

**Issue by MokoPolo** [drcika/apc-extension#124]
Apc Extension failed: Error: EACCES: permission denied, rename '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js'->'/Applications/Visual Studio
Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by MokoPolo** [comment]
Thanks. I see sudo `chown -R $(whoami) $(which code)`
What does `which code` mean?

**Comment by iknownoth1ng** [comment]
> Thanks. I see sudo `chown -R $(whoami) $(which code)` What does `which code` mean?

I guess it means directory where vscode installed

**Comment by MokoPolo** [comment]
Thanks!

**Comment by fm1randa** [comment]
`sudo chown -R $(whoami) $(which code)` doesn't work for me. I still get the same error after running `chown`.

```
Apc Extension failed: Error: EACCES: permission denied, rename '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'
```

This is what works for me:

```
sudo chown -R $(whoami) /Applications/Visual\ Studio\ Code.app
```

**Comment by mawid6** [comment]
This link does not seem to work

> https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

I have a similar issue for windows, I have created an issue for it, #142.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by smartinio** [comment]
I just ran into this again and it only worked after doing this:

```shell
sudo chown -R $(whoami) "/Applications/Visual Studio Code.app"
```

Assuming because `$(which code)` outputs `/usr/local/bin/code` rather than the path above
