### ISSUE TITLE
Getting error on linux when try to enable APC

### ISSUE THREAD

**Issue by golu7679** [drcika/apc-extension#125]
Error message: 
Apc Extension failed: Error: EACCES: permission denied, rename '/usr/share/code/resources/app/out/bootstrap-amd.js' -> '/usr/share/code/resources/app/out/bootstrap-amd.js.apc.extension.backup'

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by golu7679** [comment]
Thankx @drcika
