### ISSUE TITLE
[MacOS] Merge windows with title bar hidden

### ISSUE THREAD

**Issue by andrebrito16** [drcika/apc-extension#128]
I'm using `"titleBarStyle": "hidden",` but with this active the option to merge all windows is disabled.

I have already activated the `"window.nativeTabs": true` options. Is there any way to merge windows with titleBar hidden?

![CleanShot 2024-01-10 at 11 07 12@2x](https://github.com/drcika/apc-extension/assets/30161990/d89985e0-a184-4fd1-b679-8faa41f38810)
Merge windows works

![CleanShot 2024-01-10 at 11 07 40@2x](https://github.com/drcika/apc-extension/assets/30161990/6a0094f9-3cbc-454d-af66-8182923ceeb0)
Merge windows does not works

**Comment by ghost** [comment]
I'm not sure what you want. But you should be using this code for macOS
https://github.com/drcika/apc-extension?tab=readme-ov-file#inline-title-bar-with-traffic-light-position

**Comment by drcika** [comment]
this has nothing to do with this extension this is a question for the vscode team

**Comment by sheldonhull** [comment]
I ran into this myself and noticed any changes to apc.electron blocked native macOS tabs with the "merge all windows" from working. I left all those options disabled and it worked. The other style notes under stylesheet don't seem to impact this from working thankfully.
