### ISSUE TITLE
Add Support for Vibrancy theme

### ISSUE THREAD

**Issue by muhammadfaruq72** [drcika/apc-extension#13]
Thank you for amazing work. Is it possible to install https://github.com/EYHN/vscode-vibrancy along with apc-ecxtension. I would be really cool. Thank you.

**Comment by drcika** [comment]
that is a question for them https://github.com/illixion/vscode-vibrancy-continued 
i can modify their files, but it can lead to unexpected behaviors
maybe when I have time I will implement something similar

**Comment by drcika** [comment]
bottom line there is no need for other extensions
it turns out that this was possible all along, it just needed a little tweaking
see https://github.com/drcika/apc-extension/blob/production/demo/vibrancy.settings.json

settings are not the same for all OS
OS specific
https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions

**Comment by nuKs** [comment]
Hi, thanks for the amazing work as well.

I was wondering what your OSX version is?
Except for the main opacity setting (which includes text), It doesn't seem to work with my osx 12.6.2 setup.
I've tried multiple vibrancy settings, ultra-dark is no longer working on osx > 10.15 according to the doc you've linked.

**Comment by drcika** [comment]
13.4 (22F66) 
yes some settings are deprecated but still work
![Screenshot 2023-06-22 at 06 45 08](https://github.com/drcika/apc-extension/assets/35919606/b5d47e59-cd04-4ec6-9c09-366a896511c0)

**Comment by drcika** [comment]
strange situation, some settings work some don't, some of them produce the same results.
this work
sidebar, header , hud, fullscreen-ui, light, dark, medium-light, and ultra-dark
![Screenshot 2023-06-22 at 07 24 21](https://github.com/drcika/apc-extension/assets/35919606/b21a1369-6dd2-4638-9aef-ada152c12f6d)

**Comment by darianmorat** [comment]
No matter what I do, I cannot get the vibrancy effect

**Comment by drcika** [comment]
```
  "apc.electron": {
    "backgroundColor": "#00000000",
    "vibrancy": "under-window",
},
```
