### ISSUE TITLE
On new VSCODE update App Customise UI++ Don't work

### ISSUE THREAD

**Issue by Mceed** [drcika/apc-extension#133]
Version: 1.85.2
Date: 2024-01-18T06:40:32.531Z
Electron: 25.9.7
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.6.0

I tried reload the extensions but it dose't work :((
the custom styles, js not working :((

**Comment by ghost** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#enabling-and-disabling

**Comment by Mceed** [comment]
It works but I had to reapply the customisation data like app.imports to my settings.json from scratch!
Thanks!!!
