### ISSUE TITLE
ActivityBar not working.

### ISSUE THREAD

**Issue by CoderMungan** [drcika/apc-extension#136]
![Ekran Resmi 2024-01-21 18 15 46](https://github.com/drcika/apc-extension/assets/126997544/237510dd-02f6-45d3-8233-aba20e3ee21d)

**Comment by internpoon** [comment]
yeah, stop working after the latest VS code update

**Comment by CoderMungan** [comment]
i hope will be update too for APC fix too

**Comment by honghaoz** [comment]
This is the error I'm seeing:

![CleanShot 2024-01-25 at 11 38 48@2x](https://github.com/drcika/apc-extension/assets/3926785/f6c4e7ef-1505-4621-a205-6901785d278f)

```
Apc Extension failed: Error: EACCES: permission denied, rename '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

Source: Apc Customize Ul++ (Extension)
```

**Comment by Jhinger** [comment]
Similarly, background-image stopped working after the latest vscode update.

**Comment by heyman** [comment]
Downgrading VSCode to version `1.85.1` resolved it for me.

Here's a download link for macOS with Apple silicon:
https://update.code.visualstudio.com/1.85.1/darwin-arm64/stable

Here are instructions on how to construct download links for other platforms:
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

Don't forget to turn off auto updates.

**Comment by CoderMungan** [comment]
> Downgrading VSCode to version `1.85.1` resolved it for me.
> 
> Here's a download link for macOS with Apple silicon: https://update.code.visualstudio.com/1.85.1/darwin-arm64/stable
> 
> Here are instructions on how to construct download links for other platforms: https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions
> 
> Don't forget to turn off auto updates.

but without this need the work actually. so need the update about the extension too i mean.

**Comment by Jhinger** [comment]
> Downgrading VSCode to version `1.85.1` resolved it for me.
> 
> Here's a download link for macOS with Apple silicon: https://update.code.visualstudio.com/1.85.1/darwin-arm64/stable
> 
> Here are instructions on how to construct download links for other platforms: https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions
> 
> Don't forget to turn off auto updates.

I haven't been able to fix the activitybar or background image after downgrading (even with the example settings provided in the repo) - did you happen to change anything in order to fix those?

**Comment by CoderMungan** [comment]
> > Downgrading VSCode to version `1.85.1` resolved it for me.
> > Here's a download link for macOS with Apple silicon: https://update.code.visualstudio.com/1.85.1/darwin-arm64/stable
> > Here are instructions on how to construct download links for other platforms: https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions
> > Don't forget to turn off auto updates.
> 
> I haven't been able to fix the activitybar or background image after downgrading (even with the example settings provided in the repo) - did you happen to change anything in order to fix those?

If you downgranding, your old settings will return. I think it didn't work because it received an automatic update again. It may also be a conflict with some extensions you use.

**Comment by CassandraCat** [comment]
Sometimes my Activity Bar doesn't show up completely.

**Comment by CoderMungan** [comment]
mate @drcika i hope see that issue! 😂

**Comment by ahwelgemoed** [comment]
I also have this issue since the last 2 updates of VSCode. 

But I don't recommend not upgrading VSCode just for a Visual Extension like this. 
I had a quick look at the source code but could not spend the time to find a fix.

**Comment by drcika** [comment]
![Screenshot 2024-02-15 at 14 46 28](https://github.com/drcika/apc-extension/assets/35919606/174a248d-ac9e-4131-b1e4-d1fc3d3e05e9)
![Screenshot 2024-02-15 at 14 46 32](https://github.com/drcika/apc-extension/assets/35919606/058cad87-c0a9-4e65-8fbf-418e8b9e1d7f)
![Screenshot 2024-02-15 at 14 46 42](https://github.com/drcika/apc-extension/assets/35919606/badcf391-722c-4cb9-b6e8-15494aedf8a9)

**Comment by ahwelgemoed** [comment]
Wow, that does fix it, turns out the extension was just disabled after the update. Thanks @drcika

**Comment by drcika** [comment]
they do not want extensions of this type
they have already destroyed
https://github.com/iocave/customize-ui

**Comment by CoderMungan** [comment]
wow. i did it perfectly by the way. When i did it Enable APC extension worked! Thank you so much! can be close the this issue! @drcika 

and i wanna share my settings
```json
{
  // open json editor for settings
  "workbench.settings.editor": "json",
  "files.autoSave": "afterDelay",
  "workbench.iconTheme": "moxer-icons",
  // Change font
  "editor.fontFamily": "Geist Mono",
  "scm.inputFontFamily": "Geist Mono",
  "terminal.integrated.fontFamily": "JetBrainsMono Nerd Font",
  "chat.editor.fontFamily": "Geist Mono",
  "debug.console.fontFamily": "Geist Mono",
  "editor.codeLensFontFamily": "Geist Mono",
  "notebook.output.fontFamily": "Geist Mono",
  "markdown.preview.fontFamily": "Geist Mono",
  "editor.inlayHints.fontFamily": "Geist Mono",
  // Font size
  "editor.fontSize": 15,
  "terminal.integrated.fontSize": 14,
  // ui
  "editor.minimap.enabled": false,
  "workbench.tree.indent": 25,
  "window.commandCenter": false,
  "editor.scrollbar.vertical": "auto",
  "editor.scrollbar.horizontal": "auto",
  // APC
  "apc.activityBar": {
    "position": "bottom",
    "hideSettings": true,
    "size": 28
  },
  "apc.electron": {
    "titleBarStyle": "hiddenInset",
    "trafficLightPosition": {
      "x": 12,
      "y": 10
    }
  },
  "apc.font.family": "Geist Mono",
  "apc.monospace.font.family": "Geist Mono",
  "apc.statusBar": {
    "position": "editor-bottom",
    "height": 28,
    "fontSize": 12
  },
  // Cusom css
  "apc.stylesheet": {
    ".sidebar > .composite": "height: 12px !important",
    ".title-label": "display: none !important",
    ".title-actions": "display: none !important",
    ".tabs-and-actions-container > .editor-actions": "display: none !important",
    ".titlebar-center": "display: none !important",
    ".titlebar-right": "display: none !important",
    ".inline-tabs-placeholder": "display: none !important",
    ".split-view-view .visible": "background-color: #110f17 !important"
  },
  //Themes Customizations
  "workbench.colorCustomizations": {
    "[MoonGun Dark Nietzsche]": {
      "editor.background": "#110f17",
      "terminal.background": "#110f17",
      "activityBar.background": "#110f17",
      "statusBar.background": "#110f17",
      "editorGroupHeader.tabsBackground": "#110f17",
      "tab.inactiveBackground": "#110f17"
    }
  },
  // Misc
  "workbench.startupEditor": "none",
  "explorer.compactFolders": false,
  "editor.tabSize": 2,
  "editor.linkedEditing": true,
  "breadcrumbs.filePath": "off",
  "files.trimTrailingWhitespace": true,
  "[markdown]": {
    "files.trimTrailingWhitespace": false
  },
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "window.zoomLevel": 0,
  "typescript.updateImportsOnFileMove.enabled": "never",
  "explorer.confirmDragAndDrop": false,
  "javascript.updateImportsOnFileMove.enabled": "never",
  "githubPullRequests.pullBranch": "never",
  "console-ninja.toolsToEnableSupportAutomaticallyFor": {
    "live-server-extension": true,
    "live-preview-extension": true
  },
  "files.associations": {
    "*.html": "html",
    "*.js": "javascript"
  },
  "tailwindCSS.classAttributes": [
    "class",
    "className",
    "ngClass",
    "variant"
  ],
  "tailwindCSS.includeLanguages": {
    "html": "html",
    "javascript": "javascript",
    "css": "css",
    "python": "python"
  },
  "editor.quickSuggestions": {
    "strings": true
  },
  "tailwindCSS.experimental.configFile": null,
  "console-ninja.featureSet": "Community",
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit"
    }
  },
  "terminal.integrated.env.osx": {},
  "terminal.integrated.env.windows": {},
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "workbench.colorTheme": "MoonGun Dark Nietzsche",
  "vscode-pets.theme": "forest",
}
```

**Comment by honghaoz** [comment]
Based on error message:

> Apc Extension failed: Error: EACCES: permission denied, rename '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

The failures are caused by permission issues. 

Temporarily add "write" access for "Everyone" to the following directories fixes the extension:

- `/Applications/Visual Studio Code.app/Contents/Resources/app/out`
- `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs`
- `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench`
