### ISSUE TITLE
APC not working at all

### ISSUE THREAD

**Issue by JotaRata** [drcika/apc-extension#137]
I want to report yet another "APC not working" issue but this time no matter what I try, the extension doesn't seem to do anything more than turning the background pitch black when transparency is set to on.

![imagen](https://github.com/drcika/apc-extension/assets/36273501/85168fd1-4a99-45e1-92d9-05294285e630)

I already tried disabling the extension and re-enabling it via the command palette, I'm on Windows 11 and I'm using a local install of vscode.

vscode info:

```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.85.1 Chrome/114.0.5735.289 Electron/25.9.7 Safari/537.36
```

my user settings.json:`(copied from https://github.com/drcika/apc-extension/blob/production/demo/vibrancy.settings.json)
```
    "apc.electron": {
            "frame": false,
            "transparent": true,
            "titleBarStyle": "hiddenInset",
            "vibrancy": "ultra-dark",
            "opacity": 0.5,
            "visualEffectState": "active"
        },
        // vibrancy requires other panels to be transparent
        // see https://code.visualstudio.com/api/references/theme-color
        "workbench.colorCustomizations": {
        "editorGroupHeader.tabsBackground": "#00000000",
        "sideBar.background": "#00000000",
        "sideBarSectionHeader.background": "#00000000",
        "editor.background": "#00000000",
        "peekViewEditor.background": "#00000000",
        "peekViewEditorGutter.background": "#00000000",
        "peekViewTitle.background": "#00000000",
        "peekViewResult.background": "#00000000",
        "tab.activeBackground": "#00000000",
        "tab.inactiveBackground": "#00000000",
        "statusBar.background": "#00000000",
        "statusBar.debuggingBackground": "#00000000",
        "statusBar.noFolderBackground": "#00000000",
        "statusBarItem.activeBackground": "#00000000",
        "panel.background": "#00000000",
        "activityBar.background": "#00000000"
        }
```

**Comment by JotaRata** [comment]
I also tried copying the whole JSON at https://github.com/drcika/apc-extension/blob/production/demo/settings.json and nothing

**Comment by LiamWu50** [comment]
I also encountered the same problem

**Comment by tuxmanu** [comment]
can confirm the same. After the latest update to VSC 1.85.2 nothing works. disabling/enabling the extension did not help

**Comment by drcika** [comment]
works
![Screenshot 2024-01-22 at 11 26 35](https://github.com/drcika/apc-extension/assets/35919606/34d4f10a-ec90-42f0-ad0f-bf62a1fdeab6)

**Comment by aveaves** [comment]
Same. It suddenly stopped working. Tried reinstalling but didn't fix it.

**Comment by davidemariabusi** [comment]
Same here ☹️

After installing the latest VSCode update (v. 1.85.2) the extension stopped working. I tried disabling and re-enabling it, restarting VSCode but nothing, it doesn't work.

**Comment by ghost** [comment]
> it doesn't work.

I'm on windows. It works.

**Comment by Lucasbrunoferreira** [comment]
With me, CMD + SHIFT + P and enter the command "Enable APC extension" started working again!

**Comment by obrunofontana** [comment]
> With me, CMD + SHIFT + P and enter the command "Enable APC extension" started working again!

ITS WORKS THANKS

**Comment by aveaves** [comment]
> With me, CMD + SHIFT + P and enter the command "Enable APC extension" started working again!

Can confirm it works

**Comment by JotaRata** [comment]
It's still not working, I uninstalled the extension, installed it back today and got the same results

As stated in the title, none of the APC settings are working, the console log doesn't show anything out of place, so please don't close th issue yet as there is another user (@tuxmanu) who is experiencing the same problem as I (APC not working, Enable APC command not working too)
Attaching a video of the problem:

https://github.com/drcika/apc-extension/assets/36273501/2a67aaa6-cbf1-4497-9d22-db3b18a9598d

**Comment by HuntFeng** [comment]
I have the same issue here on PopOs 22.04 NVIDIA. 

enable apc does not work.
