### ISSUE TITLE
Importing more than one JS breaks every import

### ISSUE THREAD

**Issue by datismoa** [drcika/apc-extension#138]
```json
{
  "apc.imports": [
    "/C:/Users/someUser/a.js",
    "/C:/Users/someUser/b.js"
  ]
}
```

Separately, any of the imports would work. As soon as they are enabled at the same time, both are broken

Windows 11, the latest VS Code version

**Comment by landeholt** [comment]
noticed this on macos m1 as well, but for me the first import did work
