### ISSUE TITLE
Scroll on extensions

### ISSUE THREAD

**Issue by tutods** [drcika/apc-extension#139]
Hi
Any way of have a scroll or an ellipsis on this extensions?
<img width="358" alt="image" src="https://github.com/drcika/apc-extension/assets/18479474/d29f6c68-3b33-473b-949e-d1d1e52bc913">
Because if you have a lot of extensions you can't see all the icons.

**Comment by drcika** [comment]
![Screenshot 2024-03-01 at 22 04 02](https://github.com/drcika/apc-extension/assets/35919606/cf1198d8-57fd-4db8-ac77-e376b257b45e)
![Screenshot 2024-03-01 at 22 03 55](https://github.com/drcika/apc-extension/assets/35919606/062a632d-ee32-4e6d-9e6a-58e62bb0735e)

seems to be working fine, if you still have problems please make the relevant settings so I can reproduce
