### ISSUE TITLE
Activity bar disappears when clicking on the active tab when in "top" or "bottom" positions

### ISSUE THREAD

**Issue by DeltaRazero** [drcika/apc-extension#14]
In vanilla VSCode, clicking the active tab icon only causes the activity bar tab to collapse, but the bar with the icons stay visible. So when it's integrated into the tab, the whole tab disappears.

I guess a solution would be to block the collapse action entirely when in "top" or "bottom" positions.

**Comment by DeltaRazero** [comment]
Is this supposed to be fixed in APC v0.1.1? Unfortunately I can still reproduce the issue (using latest VSCode v1.79.2)

**Comment by drcika** [comment]
working 
macos vscode 1.80.0-insider
macos vscode 1.79.2
macos vscodium 1.79.2

I need more details 
os, settings.json etc

**Comment by DeltaRazero** [comment]
Windows 11 running a totally fresh VSCode:

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

settings.json:
```
{
    "apc.activityBar": {
        "position": "top",
        "size": 35
    }
}
```

And just for the good measure:
![issue](https://github.com/drcika/apc-extension/assets/26445643/acfd651b-be84-4fe7-82e2-8ad0e6353765)

**Comment by drcika** [comment]
this is expected behavior,

science activity bar integrated in the sidebar, when you close sidebar and activity bar is closed
when you open sidebar through the menu or ctrl+b/cmd+b activity bar opens too

**Comment by drcika** [comment]
if you want to have an activitybar and a closed sidebar, 
remove setting for activity bar

the current layout in vscode do not allows integration into tabs

it can't be blocked, I always close/open the sidebar

**Comment by DeltaRazero** [comment]
Ok, my issue is that I'm comparing behaviour to iocave's Customize UI, in which clicking on the current active "icon" doesn't close the sidebar.

In the example below I click multiple times on the 'explorer' and 'search' icons but the sidebar doesn't close (I would consider this expected behaviour), while in APC it closes the sidebar.

![nonissue](https://github.com/drcika/apc-extension/assets/26445643/c7b7d075-4bed-4e1f-97a9-ebb0f21e531e)

I'm assuming this will be marked as a non-issue then.

**Comment by drcika** [comment]
solution for you will be 
"workbench.activityBar.iconClickBehavior": "focus"

since the default behavior is that clicking on the active icon closes sidebar

but I won't block the closing sidebar
I use it all the time ctrl+b

**Comment by DeltaRazero** [comment]
> solution for you will be
> "workbench.activityBar.iconClickBehavior": "focus"

Ah thank you, that is an adequate fix for me. 👍

**Comment by drcika** [comment]
> > solution for you will be
> > "workbench.activityBar.iconClickBehavior": "focus"
> 
> Ah thank you, that is an adequate fix for me. 👍

note 
this has nothing to do with this extension
it is vscode default behavior
