### ISSUE TITLE
App Extension failed: EACCESS: Permission on Linux (Manjaro)

### ISSUE THREAD

**Issue by rbarszcz** [drcika/apc-extension#141]
can't make it work in Manjaro.. after managing to 'solve' the bootstrap-amd.js issue:
Apc Extension failed: Error: EACCES: permission denied, open '/usr/lib/code/out/main.js'

any ideas?

**Comment by tuanthien** [comment]
Took me a few minutes to find the section, it wasn't hidden before. Click on "Extension Troubles? We've Got You Covered!" in README.md. Github UI is broken cause this link anchor doesn't work on Firefox https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

> sudo chown -R $(whoami) /usr/lib/code/

**Comment by mawid6** [comment]
This link does not seem to work

> https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

I have a similar issue for windows, I have created an issue for it, #142.

**Comment by rbarszcz** [comment]
> Took me a few minutes to find the section, it wasn't hidden before. Click on "Extension Troubles? We've Got You Covered!" in README.md. Github UI is broken cause this link anchor doesn't work on Firefox https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users
> 
> > sudo chown -R $(whoami) /usr/lib/code/

i did that, then i kept getting errors for other files (i gave access to the user for it aswell) 
i gave up at some point, it kept throwing more and more errors, but the main features are working.. but inside vscode when i try to open a new window it breaks electron on this new window.. i just have to open a new vscode window from the apps menu.

**Comment by CaioVSales** [comment]
First disabling and then enabling worked for me through the command palette on ubuntu, (you must restart the vs code).

**Comment by tuanthien** [comment]
> This link does not seem to work
> 
> > https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users
> 
> I have a similar issue for windows, I have created an issue for it, #142.

@mawid6 The link does work because Github UI is broken.  Click on "Troubleshooting Extension Issues!" in README.md will show you where the link should have lead to.

@rbarszcz i suspect your vscode installation folder is `/usr/lib/code`, if not adjust accordingly. Maybe you forgot to run the command "Enable Apc extension" after.

I set the current user to own the installation folder (Arch Linux in my case) then run command "Enable Apc extension". I do this every time after i update vscode, works just fine.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users
