### ISSUE TITLE
Re-enabling after reload requires admin to avoid perm issue (WIN)

### ISSUE THREAD

**Issue by chipbite** [drcika/apc-extension#142]
Hi! Thanks for a great extension.
This issue has a simple workaround, but it is abit annoying and may be problematic for some users.

**Story:** After updating vs code, it seems I have to re-enable the apc extension using `Enable Apc Extension` command.
**Issue:** The issue when doing that is that what often seems to happen is a file permissions error.

The message that is displayed is:

```
﻿Apc Extension failed: Error: EPERM: operation not permitted, 
rename 'c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js' -> 'c:\Program Files\Microsoft VSCode\resources\app\out\bootstrap- amd.js.apc.extension.backup'
Source: Apc Customize Ul++ (Extension)
```

**Workaround**: 
* Close vs code, 
* start vs code as admin and 
* enable apc, which then seems to work. 
* Close vs code and start it again, now as normal user, not admin. 
* apc stays enabled.

------

I hope this can be reproduced and confirmed. 

Since the issue has a workaround, it is not so critical, IMHO.

I am not sure if and how this can be resolved but I propose to either: (1) Fix / avoid the issue, if possible (duh), or (2) Catch this error and clarify to the user what needs to be done and/or where more details can be read/found (3) update readme with information on this issue. 

I searched and could not find any info or mention of this issue. 

There are two issues with similar problems for linux/mac but I did not get the the link to info that was provided there to work.

------

![image](https://github.com/drcika/apc-extension/assets/77722885/f8cca6f0-001a-4fa5-9fb3-7069a9f6a01d)

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users
