### ISSUE TITLE
Question: How do I show the file name in the status bar ?

### ISSUE THREAD

**Issue by TheDataSeneschal** [drcika/apc-extension#145]
Hey there! I've been playing around with the APC extension in VSCode and was wondering if there's a way to get the current file name to show up in the status bar.

I tried the below but it didn't work.
`"apc.statusBar": {`
  `"position": "bottom",`
  `"height": 22,`
  `"fontSize": 12,`
  `"showFileName": true`
}

**Comment by rez1-dev** [comment]
Not possible with default settings. You can use [better status bar](https://marketplace.visualstudio.com/items?itemName=RobertOstermann.better-status-bar)
