### ISSUE TITLE
Shows read-only file system error upon install.

### ISSUE THREAD

**Issue by AsadNoman** [drcika/apc-extension#149]
Apc Extension failed: Error: EROFS: read-only file system, rename '/snap/code/150/usr/share/code/resources/app/out/bootstrap-amd.js' -> '/snap/code/150/usr/share/code/resources/app/out/bootstrap-amd.js.apc.extension.backup'

**Comment by MFattakhov** [comment]
Same issue

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by Act0r1** [comment]
> https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

This is don't work

**Comment by oviniciusfeitosa** [comment]
Same issue here.

**Comment by 0xWeverton** [comment]
its worked for me in cursor:

1. Open a terminal and navigate to the directory where you downloaded the AppImage.

2. Make the AppImage executable:

   ```bash
   chmod +x cursor-0.40.4x86_64.AppImage
   ```

3. Create a new directory to extract the content:

   ```bash
   mkdir ~/cursor-extracted
   ```

4. Extract the contents of the AppImage:

   ```bash
   ./cursor-0.40.4x86_64.AppImage --appimage-extract
   ```

5. Move the extracted content to the new directory:

   ```bash
   mv squashfs-root/* ~/cursor-extracted/
   ```

6. Create a startup script for Cursor:

   ```bash
   cat << EOF > ~/run-cursor.sh
   #!/bin/bash
   export TMPDIR=\$HOME/cursor-temp
   mkdir -p \$TMPDIR
   cd ~/cursor-extracted
   ./AppRun "\$@"
   EOF
   ```

 This script sets up a custom temporary directory to avoid permission issues.

7. Make the script executable:

   ```bash
   chmod +x ~/run-cursor.sh
   ```

8. Run Cursor using the new script:

   ```bash
   ~/run-cursor.sh
   ```
