### ISSUE TITLE
vscode completly broken after enabled and disabled

### ISSUE THREAD

**Issue by alex-suarez-lmnd** [drcika/apc-extension#153]
<img width="1728" alt="Screenshot 2024-02-19 at 8 16 28 PM" src="https://github.com/drcika/apc-extension/assets/7695887/f522569c-41fc-4fd1-9a00-44a300c20f03">
 Even reinstalling does not solve the issue

**Comment by alex-suarez-lmnd** [comment]
Also wit the extension enabled I can access anything, not the terminal or the sidebar or the project
<img width="1728" alt="Screenshot 2024-02-19 at 9 16 31 PM" src="https://github.com/drcika/apc-extension/assets/7695887/7379e5e8-d478-4d37-b982-eea4159fb318">

**Comment by gabeknob** [comment]
My extensions pane loads forever when apc is enabled

**Comment by mon-jai** [comment]
After reinstalled VSCode, you will be prompted to restart VS Code, click "Cancel".

![image](https://github.com/drcika/apc-extension/assets/91261297/66988fd7-c8f6-4a4c-839b-53f144a2fcab)

Then, invoke the command panel with Ctrl+Shift+P, type "disable apc extension" in it and press Enter.

![image](https://github.com/drcika/apc-extension/assets/91261297/4260ea4c-dd17-44b1-ac74-df5a7acedaa6)

That should leave you with an intact installation.

**Comment by GabrielVictorF** [comment]
> After reinstalled VSCode, you will be prompted to restart VS Code, click "Cancel".
> 
> ![image](https://private-user-images.githubusercontent.com/91261297/307452659-66988fd7-c8f6-4a4c-839b-53f144a2fcab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzA4MzUsIm5iZiI6MTcwOTE3MDUzNSwicGF0aCI6Ii85MTI2MTI5Ny8zMDc0NTI2NTktNjY5ODhmZDctYzhmNi00YTRjLTgzOWItNTNmMTQ0YTJmY2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAxMzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NjdmYzE0ZDQyOTg3NDgxNDYxMmJhOTNlZmU4MGYxZTU1NmIwZTZhY2I4Nzk1ZjE1OWNmNTBiODA3MTY5MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rsIUgP2eG2EWN8eRLm6eUwZovOTYGzppxsAw03QnAdQ)
> 
> Then, invoke the command panel with Ctrl+Shift+P, type "disable apc extension" in it and press Enter.
> 
> ![image](https://private-user-images.githubusercontent.com/91261297/307452875-4260ea4c-dd17-44b1-ac74-df5a7acedaa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzA4MzUsIm5iZiI6MTcwOTE3MDUzNSwicGF0aCI6Ii85MTI2MTI5Ny8zMDc0NTI4NzUtNDI2MGVhNGMtZGQxNy00NGIxLWFjNzQtZGY1YTdhY2VkYWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAxMzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MWE1ZTc3ODFjY2JlMzFjMThlN2FmN2Q5OThjMzEyM2Q5NTk1NDRhYTNiYWZjOWJkNWNjN2JmYjdhMzkzODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Crt6aODEHPPbySNT6ClyS5rk7yzmfCIiI8fULWE-2jA)
> 
> That should leave you with an intact installation.



> My extensions pane loads forever when apc is enabled

Also my debug not working

**Comment by GabrielVictorF** [comment]
> My extensions pane loads forever when apc is enabled

Also my debug not working

**Comment by diegxperez** [comment]
I even installed an older version of vs code, and used "extensions.supportUntrustedWorkspaces" but I can't fix it yet

**Comment by MateusJSouza** [comment]
Same problem here after installing the new VSCode update

**Comment by alex-suarez-lmnd** [comment]
As an update, the only solution for this is to completely remove vscode and install it again, just uninstalling does not solves the issue, meaning you need to remove vscode from applications but also manually delete the vscode folder called `code`

1. Go to your Applications folder and drag Visual Studio Code to the Trash.
2. Click on the Finder icon in the Dock and then the Go menu.
3. Choose Go to Folder.
4. Type this path in the text box: ~/Library/Application Support and press Return.
5. Look for files or folders with ‘Code’ or ‘vscode’ in their name.
6. Drag them to the Trash.
7. Empty the Trash.

This should do it 

PS: For those using windows this post shows how to find the `code` folder
