### ISSUE TITLE
APC extension stops working after vsCode update - current VSCode version 1.87.0

### ISSUE THREAD

**Issue by kalpeshdhotre** [drcika/apc-extension#155]
## Does anyone facing problem after Vscode update APC extension is not working. 

This I noticed after few updates.  
VsCode 1.85.2 it was working Then after on every update extension APC is not working.

to solve this - turnaround is unistall VsCode completely ( after deleting %USERPROFILE%\.vscode and %APPDATA%\Code)
reinstall VsCode and then Apply APC. 

does anyone facing same problem and if any solution found to this behaviour? 

>following are the setttings in my settings.json
```
"apc.listRow": {
       "lists": ["explorer-folders-view"],
       "fontSize": 14,
       "height": 20
    },

   
    "apc.stylesheet": {
       ".explorer-folders-view": "zoom: 1.05; transform-origin: 0 0;",
       ".monaco-workbench .part.editor>.content .editor-group-container>.title div.tabs-container": "border-radius: 5px; font-family: 'Iosevka Aile KD Light', Times, serif;"
    },
    "apc.font.family": "Iosevka Aile KD Light",
```

**Comment by kalpeshdhotre** [comment]
Going  to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
Type "Enable Apc extension" to enable

Resolves!! Thanks

**Comment by kalpeshdhotre** [comment]
are you talking about this search ?
![image](https://github.com/drcika/apc-extension/assets/49611334/11eae981-6cb2-4f00-b39d-802ae568b36e)
if i have misunderstood - please share screenshot 
and elaborate on problem.

**Comment by ghost** [comment]
I am having the same problem as scruch. The extention tab area (where you typically manage your extentions) fails to load while APC is enabled since the new update.

**Comment by drcika** [comment]
Disable Apc extension 
update Apc extension v0.3.7
Enable Apc extension
