### ISSUE TITLE
Blur effect not working on macOS Sonoma 14.3

### ISSUE THREAD

**Issue by andredichev** [drcika/apc-extension#156]
I am trying to get a transparency effect and a blur effect, however the transparency effect works, but the blur effect does not. I have tried all versions of VSCode from 1.84 to the latest version currently available (1.87). I am using macOS Sonoma version 14.3. 

I have also tried different `vibrancy` values, however none of them produced a positive result.

![ScreenCapture 2024-03-01 at 18 28 07](https://github.com/drcika/apc-extension/assets/49833005/4fabe9d6-e64e-4dbc-b4d2-d87ebb216d25)

**Comment by drcika** [comment]
```
  "apc.electron": {
    "backgroundColor": "#00000000",
    "vibrancy": "under-window",
},
```

other panel must be transparent 
```
  "workbench.colorCustomizations": {
    "editorGroupHeader.tabsBackground": "#00000000",
    "sideBar.background": "#00000000",
    "sideBarSectionHeader.background": "#00000000",
    "editor.background": "#00000000",
    "peekViewEditor.background": "#00000000",
    "peekViewEditorGutter.background": "#00000000",
    "peekViewTitle.background": "#00000000",
    "peekViewResult.background": "#00000000",
    "tab.activeBackground": "#00000000",
    "tab.inactiveBackground": "#00000000",
    "statusBar.background": "#00000000",
    "statusBar.debuggingBackground": "#00000000",
    "statusBar.noFolderBackground": "#00000000",
    "statusBarItem.activeBackground": "#00000000",
    "panel.background": "#00000000",
    "activityBar.background": "#00000000"
  }
```

**Comment by mv-stns** [comment]
Unfortunately this only works for bright themes, not for dark ones (or even system wide darkmode)

**Comment by pranav-js** [comment]
thanks man! @drcika  do you know how to fix transparency for sticky scroll part

![CleanShot 2024-09-01 at 12 38 01@2x](https://github.com/user-attachments/assets/e90191f4-8b0e-4fee-b159-c7018612a17f)

**Comment by kyds3k** [comment]
> thanks man! @drcika do you know how to fix transparency for sticky scroll part
> 
> ![CleanShot 2024-09-01 at 12 38 01@2x](https://private-user-images.githubusercontent.com/79982692/363465701-e90191f4-8b0e-4fee-b159-c7018612a17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU0NDgsIm5iZiI6MTcyNzMzNTE0OCwicGF0aCI6Ii83OTk4MjY5Mi8zNjM0NjU3MDEtZTkwMTkxZjQtOGIwZS00ZmVlLWIxNTktYzcwMTg2MTJhMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTA0MThmNTA4YTFkYThkNWJkYTM1YzE4NGI5ODNlNWNlOTQ3NWYzMDBmOGVjZTFkMTdlNzBhYmEyNjIzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vo1XyHIXTY0ciT5hMciY1Bu8toEhvVlMCIRVYBaYm8k)

@pranav-js did you figure this out? having the same problem.

**Comment by NateRobinsonAA** [comment]
> > thanks man! [@drcika](https://github.com/drcika) do you know how to fix transparency for sticky scroll part
> > ![CleanShot 2024-09-01 at 12 38 01@2x](https://private-user-images.githubusercontent.com/79982692/363465701-e90191f4-8b0e-4fee-b159-c7018612a17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU0NDgsIm5iZiI6MTcyNzMzNTE0OCwicGF0aCI6Ii83OTk4MjY5Mi8zNjM0NjU3MDEtZTkwMTkxZjQtOGIwZS00ZmVlLWIxNTktYzcwMTg2MTJhMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTA0MThmNTA4YTFkYThkNWJkYTM1YzE4NGI5ODNlNWNlOTQ3NWYzMDBmOGVjZTFkMTdlNzBhYmEyNjIzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vo1XyHIXTY0ciT5hMciY1Bu8toEhvVlMCIRVYBaYm8k)
> 
> [@pranav-js](https://github.com/pranav-js) did you figure this out? having the same problem.

It seems to be tied to "editor.background". I set mine to half-transparent:

```json
"editor.background": "#00000090",
```

EDIT: It's directly styled by `editorStickyScroll.background`
