### ISSUE TITLE
APC is crashing loading the extensions in vscode

### ISSUE THREAD

**Issue by JulindM** [drcika/apc-extension#160]
The resolution discussed at the end of this vscode thread, points to APC crashing vscode's loading extensions.

https://github.com/microsoft/vscode/issues/206522

**Comment by drcika** [comment]
disable apc extension 
update apc extension 
enable apc extension

**Comment by JulindM** [comment]
The problem is I cannot even open the extensions window. The whole extensions tab does not load anything, so you cannot even disable or update it!

**Comment by JulindM** [comment]
You need to reinstall vscode from the beginning to be able to resolve the issue.

**Comment by drcika** [comment]
![Screenshot 2024-03-05 at 11 11 30](https://github.com/drcika/apc-extension/assets/35919606/d0ba9639-2393-49bf-8886-98bf3df940e7)
no need to reinstall

**Comment by JulindM** [comment]
Oh ... thanks for your input. I didn't know this quick action existed.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#enabling-and-disabling
