### ISSUE TITLE
feat:-request: rounded vscode window and traffic light

### ISSUE THREAD

**Issue by its-19818942118** [drcika/apc-extension#161]
is it possible add mac os look and feel to windows and linux vscode version cuz it would be great if that is possible :) cuz there are extension for mac os traffic light but doesnt feel very native and clean experience,
and most of all there are no rounded corners

**Comment by drcika** [comment]
this extension provides the possibility for the user to customize the appearance of vscode,
no default settings come with this extension


however, your wish cannot be fulfilled at all, because it is part of the operating system, in the best case scenario all possible solutions can only mimic.

**Comment by its-19818942118** [comment]
Thanks for letting me know I have switched to arch Linux. And rounded corners work :)

**Comment by joaomedeirosr** [comment]
hey @its-19818942118 in the arch the rounded corners are native ? or you change with apc? if you change how you do this?

**Comment by its-19818942118** [comment]
> hey @its-19818942118 in the arch the rounded corners are native ? or you change with apc? if you change how you do this?

@joaomedeirosr welp I my case my titling window manager hyprland handles the look and feel of the window so I set it up as rounded corners and it works. I don't need traffic lights so. It works for me this are all done by the window manager for windows it won't work unless the app handles it. Hypr terminal has that rounding effect but since vscode doesn't natively support rounded corners on windows it just won't work 🙁
