### ISSUE TITLE
An error message appears in the developer console

### ISSUE THREAD

**Issue by alaric8** [drcika/apc-extension#165]
auxiliary.js:31 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at toggleSettings (layout.activitybar.js:17:56)
    at exports.init (layout.activitybar.js:161:11)
    at exports.init (layout.js:10:21)
    at exports.startup (override.js:10:14)
    at where.<computed> (utils.js:8:26)
    at se.open (workbench.desktop.main.js:sourcemap:2793:120327)
    at async workbench.js:2604:6
exports.traceError @ auxiliary.js:31

**Comment by drcika** [comment]
sync version 0.3.8 no longer supported apc.activityBar.hideSettings
use "window.customTitleBarVisibility": "never"
https://github.com/drcika/apc-extension?tab=readme-ov-file#apcactivitybar 

disable apc extension 
update apc extension
enebale apc extension

**Comment by alaric8** [comment]
#apc extension version  0.3.9

# vscode version info  
版本: 1.85.2 (user setup)
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

# setting.json
```json
{
"apc.menubar.compact": true,
    "apc.electron": {
        "frame": false,
        // "transparent": true,
        // "titleBarStyle": "hiddenInset",
        // "vibrancy": "ultra-dark",
        // "opacity": 0.98,
        // "visualEffectState": "active"
    },
    "apc.stylesheet": {
   ".explorer-folders-view .editor-group,.explorer-folders-view .explorer-item ": "line-height: 27px;"
  },
    "apc.listRow": {
        "fontSize": 18,
        "height": 28,
        "lists": [
          "explorer-folders-view"
        ],
        "parts": {}
      },
}
```
# error info 
 WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
auxiliary.js:31 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at toggleSettings (layout.activitybar.js:17:56)
    at exports.init (layout.activitybar.js:161:11)
    at exports.init (layout.js:10:21)
    at exports.startup (override.js:10:14)
    at where.<computed> (utils.js:8:26)
    at se.open (desktop.main.ts:129:42)
    at async workbench.js:2595:6
exports.traceError @ auxiliary.js:31

**Comment by alaric8** [comment]
vscode 1.8.8 insider version also has the same problem

**Comment by drcika** [comment]
i can't reproduce
![Screenshot 2024-03-08 at 05 18 00](https://github.com/drcika/apc-extension/assets/35919606/f41c301f-b6ff-49e8-a166-126ee7a682e3)

**Comment by AlaricWeb** [comment]
不好意思，我发现不是这个插件错误,是官方语言包的错误

**Comment by alaric8** [comment]
Sorry, I found that it is not an error with this plug-in, but an error with the official language pack.
