### ISSUE TITLE
apc.imports doesn't seem to work

### ISSUE THREAD

**Issue by deanm0000** [drcika/apc-extension#166]
I'm trying to make it so that the cells I'm working with reflect the same CSS file that nbconvert incorporates. I added

```
    "apc.imports": [
        
        "${userHome}/.jupyter/custom/custom.css"
    ]
```

to my `settings.json` but my notebook cells aren't reflecting the css. When I do `jupyter nbconvert ...` the output html has the css built in so it's valid css. Am I doing something wrong or expecting the wrong thing?

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#apciframestyle

**Comment by lakshits11** [comment]
Hy @deanm0000 , can you share your jupyter stylesheet please. Thank You.

**Comment by deanm0000** [comment]
```
.row {
    display: flex;
}

.leftcol {
    flex: 10%;
}
.rightcol {
    flex: 80%;
}
.draft {
    font-size: 30px;
}
.units {
    font-size: 10px;
    text-align: center;
}
.coltitle {
    text-align: right;
}
```
