### ISSUE TITLE
Useing Electron accelerators.

### ISSUE THREAD

**Issue by Digital-gitz** [drcika/apc-extension#167]
I want to be able to implement accelerator module to be able to use VS-code with a Global Hotkey, I don't believe I can use the provided  function method call  BrowserWindow([options]) but when I looked into how you implemented apc-extension I saw that it might originate somewhere in the main.js file where I could implement accelerator. I don't have an idea how to do this or if i could access it through the JSON options,  dose anyone have an idea of what I could do? ... now that I'm looking at the extension code I wonder If I could fork and try to implement that way... though if anyone have solution would be great.♥️

**Comment by drcika** [comment]
It's possible
![Screenshot 2024-03-11 at 06 23 51](https://github.com/drcika/apc-extension/assets/35919606/eb52668b-b791-4462-9bb9-2e8a6e654b52)
what would you like to do?
