### ISSUE TITLE
Title Bar Customization Setting Conflicts with Context Menu Style

### ISSUE THREAD

**Issue by alnahian2003** [drcika/apc-extension#168]
![image](https://github.com/drcika/apc-extension/assets/61485238/c4937d4f-b2f6-413c-b610-df4ead9e1a66)

Hey, I've just customized my code editor with this extension, and I'm satisfied. However, when I set some settings for the Title Bar like this:

```json
"apc.electron": {
  "titleBarStyle": "hidden"
},
"window.titleBarStyle": "native",
"window.customTitleBarVisibility": "never"
```

It hides the title bar, which is what I want. Unfortunately, this also sets the Context Menu style to Windows native style, which is not what I want. I prefer the default context menu style.

![image](https://github.com/drcika/apc-extension/assets/61485238/2045db72-8066-4988-b587-882be7c44105)
![image](https://github.com/drcika/apc-extension/assets/61485238/be676b49-85c8-4abe-b55d-0b0415a3515a)

Is there any way I can fix this in Windows 10? Here's the VS Code version:

```
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

Thank You, have a great day!

**Comment by drcika** [comment]
It's because
"window.titleBarStyle": "native"
"Adjust the appearance of the window title bar to be native by the OS or custom. On Linux and Windows, this setting also affects the application and context menu appearances. Changes require a full restart to apply."

it has nothing to do with this extension

**Comment by alnahian2003** [comment]
Thank you. That makes sense. One last question, can I hide this project title and file name from the title bar and keep the rest visible?
![image](https://github.com/drcika/apc-extension/assets/61485238/1ac794bb-d449-4140-b878-21b0d98f9e1e)

This will make my customization 100% completed!

**Comment by drcika** [comment]
```
  "apc.stylesheet": {
    ".window-title": {
      "display": "none"
    }
  }
```

**Comment by alnahian2003** [comment]
Thanks a zillion @drcika! I owe you one ⚡

![image](https://github.com/drcika/apc-extension/assets/61485238/d4ca1d2c-c4a3-4f2e-80c9-d097ccec5d44)

Now my editor looks extremely clean, elegant and beautiful!
