### ISSUE TITLE
Is it possible to remove this white line between status bar on macos and vscode?

### ISSUE THREAD

**Issue by sobolevn** [drcika/apc-extension#169]
Hi! Thanks a lot for this amazing extensions, I like it very much.
Question / feature proposal: is it possible to remove this? 
<img width="1334" alt="Снимок экрана 2024-03-19 в 12 33 31" src="https://github.com/drcika/apc-extension/assets/4660275/7e43c721-3e7a-4ee0-9884-a29c31b6b340">

Do you see this white line? It is an old electron bug on macos or something, it was around since Catalina? I guess.

https://github.com/microsoft/vscode/issues/144389

**Comment by sobolevn** [comment]
```
"apc.electron": {
      "frame": false,
      "transparent": true,
}
```

Solved this for me!

<img width="1352" alt="Снимок экрана 2024-03-19 в 12 41 56" src="https://github.com/drcika/apc-extension/assets/4660275/c9daf5fe-cd97-4bfd-a176-8229acd93e93">

Thank you, this is amazing!

**Comment by niemes** [comment]
> ```
> "apc.electron": {
>       "frame": false,
>       "transparent": true,
> }
> ```
> 
> Solved this for me!
> <img alt="Снимок экрана 2024-03-19 в 12 41 56" width="1352" src="https://private-user-images.githubusercontent.com/4660275/314001373-c9daf5fe-cd97-4bfd-a176-8229acd93e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMDYzNTYsIm5iZiI6MTcxMjAwNjA1NiwicGF0aCI6Ii80NjYwMjc1LzMxNDAwMTM3My1jOWRhZjVmZS1jZDk3LTRiZmQtYTE3Ni04MjI5YWNkOTNlOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMjExNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE3YjhhMTJhYTUxY2Q5NTRlYzQzODA2M2MwZDZlOTZlNDExMTgyYjMxZmExYjdiNTRjYzhiZmYzMjhiMDY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-fLiBiWUwy0SVZICQUcpDeGS8cWaIdm4awqnwh9EZOU">
> 
> Thank you, this is amazing!

Hey, I try the same code and MacOs white border are still there. What did you do to get ride of them ?

I installed the extension, added the style in settings.json
Executed sudo chown -R $(whoami) $(which code)
Rebooted my Mac

Still have those horrible lines... Am I missing something ?

<img width="1710" alt="Screenshot 2024-04-02 at 00 20 02" src="https://github.com/drcika/apc-extension/assets/6246777/1dbb57df-187a-4104-bf7b-43bd0698af10">

MacOs Sonoma 14.3

**Comment by sobolevn** [comment]
You can check my dotfiles: https://github.com/sobolevn/dotfiles
It is a complete and up-to-date collection of all the settings I use.

**Comment by ueoo** [comment]
Hi, as the latest VSCode breaks the `apc-extension`, is there any other way to do so?
Thanks
