### ISSUE TITLE
Apc Extension failed: Error on Mac

### ISSUE THREAD

**Issue by ahmedhelow** [drcika/apc-extension#170]
I am trying to instal Vscode Animations but keep getting this error: 
`Apc Extension failed: Error: EROFS: read-only file system, rename '/private/var/folders/5n/33v522z50slgj1pdrflw8s0m0000gp/T/AppTranslocation/DE04D657-210E-4A14-B434-C9376524C04B/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/private/var/folders/5n/33v522z50slgj1pdrflw8s0m0000gp/T/AppTranslocation/DE04D657-210E-4A14-B434-C9376524C04B/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'`

I found this problem for someone running ubunto, but couldn't find a solution for mac?

**Comment by macianaa** [comment]
Hey @ahmedhelow, have you found a solution?

**Comment by macianaa** [comment]
> Hey @ahmedhelow, have you found a solution?

I managed to find the cause of this - you need to move VSCode to application folder in Finder.

**Comment by ahmedhelow** [comment]
> > Hey @ahmedhelow, have you found a solution?
> 
> 
> 
> I managed to find the cause of this - you need to move VSCode to application folder in Finder.

Yes, that was it. I was trying to remember what did I do but you figured it out. 👏
