### ISSUE TITLE
EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by vilpessoa** [drcika/apc-extension#178]
**Não funciona no VS Code:**
Versão: 1.84.2 (system setup)
Confirmar: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Data: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
SO: Windows_NT x64 10.0.22631

![image](https://github.com/drcika/apc-extension/assets/151377416/ec6bf6bb-4edb-457f-b49f-67110bda9561)

![image](https://github.com/drcika/apc-extension/assets/151377416/c1a1afc5-d076-489f-97ed-3b7a5d1c650c)

**Comment by Eveeifyeve** [comment]
This is what is happens to nix on #177 It seems to be a common issue and thats why there is a read me with the common paths.

**Comment by Eveeifyeve** [comment]
I am looking to find the issue and see if you can get some sort of `sudo` access if possible and fix it.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#mac-and-linux-users

**Comment by vilpessoa** [comment]
The "Enable Apc extension" command doesn't work for me.
Do I have another problem?

**Comment by nodgear** [comment]
The readme has a section literally about that.
just fix your permissions on the vscode profile folder.

**Comment by yorks-dev** [comment]
Please look here for a detailed guide : https://github.com/drcika/apc-extension/issues/177#issuecomment-2095826726

If you are using Nix or your installation dir is not writable then you have to change permissions.
