### ISSUE TITLE
Draggable tab area that is empty

### ISSUE THREAD

**Issue by SilverMarcs** [drcika/apc-extension#18]
It would be nice for "editorGroupHeader.tabsBackground" to be draggable when no tabs are taking up that area. Makes more dragging area available other than just the sidebar top area. I'm aware there is a very thin line at the very top that is draggable but that can often be hard to take cursor to

**Comment by drcika** [comment]
while waiting for an update
settings.json
```
  "apc.stylesheet": {
    ".content.empty+.inline-drag-placeholder" {
      "height": "var(--header-height)",
      "background-color": "rgba(0, 0, 0, 0.05)"
    }
  }
  ```
or custum.css if you have 
```
.content.empty+.inline-drag-placeholder {
    height: var(--header-height);
    background-color: rgba(0, 0, 0, 0.05);
}
```

**Comment by SilverMarcs** [comment]
That didn't quite work for me. This worked though:

```
".tabs-container": "-webkit-app-region: drag",
".tab": "-webkit-app-region: no-drag",
```

setting the draggable property of .tabs-container to `false` also gets rid of the current filename from being dragged with the cursor.

**Comment by drcika** [comment]
now you can't anymore drag&drop(reorder) tabs...

other problems that I know  tabs scroll, dblclick to create new file, drag file from exploer to open etc
so I can't just insert a div or add -webkit-app-region 

if I find a suitable solution, I will implement it 

if you are satisfied with your solution, cool 
but that cannot be a general solution

**Comment by drcika** [comment]
> That didn't quite work for me. This worked though:
> 
> ```
> ".tabs-container": "-webkit-app-region: drag",
> ".tab": "-webkit-app-region: no-drag",
> ```
> 
> setting the draggable property of .tabs-container to `false` also gets rid of the current filename from being dragged with the cursor.

actuli this seems to be a good solution

**Comment by SilverMarcs** [comment]
> tabs scroll, dblclick to create new file, drag file from exploer to open

These seem to be working, but yeah good to watch out for other edge cases before generalizing this. The original Customize UI had this functionality already. Could be worthwhile to find out what they did.

**Comment by drcika** [comment]
it seems to work(only draging)
I saw their solution, they had some problem, I don't remember exactly which one, that's why I didn't implement the same, I think it was a problem with dbclick
