### ISSUE TITLE
real time css import on windows only works if file path is formatted unix style

### ISSUE THREAD

**Issue by yg-i** [drcika/apc-extension#182]
On Win10, I tried this style of filepath per the readme, but while the .css is successfully imported, there's no live update

```
	"apc.imports": [
		"/C:/code/style1.css",
		"/C:/code/style2.css"
	],
```

I solved this problem by changing the filepath to:
```
	"apc.imports": [
		"/code/style1.css",
		"/code/style2.css"
	],
```
And now live update works.

Probably due to some quirk to do with fileService.onDidFilesChange, but just FYI

**Comment by rez1-dev** [comment]
Yes, that is documented [apc.imports](https://github.com/drcika/apc-extension?tab=readme-ov-file#apcimports)
