### ISSUE TITLE
Unable to achieve complete titleBar compression on VSCodium

### ISSUE THREAD

**Issue by zeroaddresss** [drcika/apc-extension#183]
I am trying to tweak APC settings in order to make my titleBar look like this:
![image](https://github.com/drcika/apc-extension/assets/97956131/23ff7fad-804c-4ddb-9a09-ac204feccb96)

However, as you can see from the picture attached below, the `window` objects (lines 9-10-11) are shadowed and I can not achieve the behavior I am looking for. Indeed, the opened tabs are located below the traffic lights, instead of being on the right.
From the same screenshot, you can also see all of my APC settings if that can help for debugging.
Perhaps, there has been any VSCode/ium update that no longer uses `window` objects and they have been replaced?
I have tried to debug this issue myself but none of my attempts managed to fix it.
<img width="1438" alt="image" src="https://github.com/drcika/apc-extension/assets/97956131/c76ffebb-cebe-4ab0-ad66-bccf78aa4ab2">

**Comment by rez1-dev** [comment]
Did you use this section code?
https://github.com/drcika/apc-extension?tab=readme-ov-file#inline-title-bar-with-traffic-light-position

**Comment by rez1-dev** [comment]
That's not an extension related issue. You should update vscodium to latest version.

As far as I know, vscode marketplace isn't supported in vscodium by default. In that case, download the `.vsix` file from [marketplace](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension) version history
