### ISSUE TITLE
Is it possible to modify VScode source files instead of installed version?

### ISSUE THREAD

**Issue by sergei-dyshel** [drcika/apc-extension#185]
I'm using a custom fork of VScode so I would like to take changes that the extension does to locally installed version.

For example, I only want to remove titlebar using the following config.
```
    "apc.electron": {
      "titleBarStyle": "hidden",
    },
```

Is there some guide or instructions on how to do that?

PS. I guess this is not quite an "issue" I couldn't find a more appropriate place to post that.

**Comment by drcika** [comment]
https://github.com/microsoft/vscode/blob/95e2edd48f91bcd2429081f1f4cec9e2eb265a7c/src/vs/platform/windows/electron-main/windowImpl.ts#L615
