### ISSUE TITLE
mac,  use activityBar.position: "top" but can't click

### ISSUE THREAD

**Issue by FiyZou** [drcika/apc-extension#188]
![20240531164621](https://github.com/drcika/apc-extension/assets/26448696/194e7b1c-5f80-4490-b502-a48699f49970)

vscode version: 1.89.1

**Comment by noahwaldner** [comment]
I'm experiencing the same behavior

**Comment by masterr115** [comment]
Same here! Did you find a solution?

**Comment by FiyZou** [comment]
I updated to the latest version of VS Code, used its provided activity bar settings, and set it to the top.
![image](https://github.com/user-attachments/assets/b5e34859-2b9e-4741-a80c-41b25bd77f42)
