### ISSUE TITLE
I don't want to minimize/maximize by double click on titlebar

### ISSUE THREAD

**Issue by anwarulislam** [drcika/apc-extension#189]
I am on a macOS. And my settings json below. When I click on a title bar to open a new tab it minimizes my entire vscode. I don't want to minimize vscode when double clicking on a titlebar

```json
  "workbench.activityBar.location": "top",
  "window.customTitleBarVisibility": "never",
  "window.titleBarStyle": "native",
  "apc.electron": {
    "titleBarStyle": "hiddenInset",
    "trafficLightPosition": {
      "x": 10,
      "y": 10
    }
  },
  "apc.activityBar": {
    "size": 90,
    "itemSize": 33
  },
  "apc.stylesheet": {
    ".mac .sidebar .composite-bar-container": "padding-left: 70px",
    ".mac .inline-titlebar-placeholder": "padding-left: 0 !important"
  },
```

**Comment by 1zumii** [comment]
i come across the same issue, and find a workaround that modify the behavior of system on double click window

1. open system setting
2. go to docker setting
3. set `Double-click a windows title bar to` do nothing

but this takes effect on all windows

**Comment by anwarulislam** [comment]
@1zumii yeah, also on double click it should open a new tab. which is not working too. It only works when no tab is open there.

**Comment by rez1-dev** [comment]
> It only works when no tab is open there.

The reason is simple: you're merging title bar with tab bar. It's like one tab fully stretched out. So, it won't open a new tab like normal vscode should do.
