### ISSUE TITLE
Bottom ActivityBar overlapping with sidebar border

### ISSUE THREAD

**Issue by SilverMarcs** [drcika/apc-extension#19]
<img width="287" alt="image" src="https://github.com/drcika/apc-extension/assets/77480421/04e67fe6-8ee6-44bf-acd6-7c000d039703">

When `sideBar.border` has a color, bottom activity bar seems to overlap with it. resulting in the situation in the image. Toggling activity bar to be invisible restores the border area there. This overlap scales with the size/height of activity bar

**Comment by drcika** [comment]
pls settings how to reproduce 
![Screenshot 2023-06-22 at 18 55 31](https://github.com/drcika/apc-extension/assets/35919606/52fe640e-57b9-4044-b6d9-7a64abb18087)

**Comment by SilverMarcs** [comment]
```
  "workbench.colorCustomizations": {
      "sideBar.background": "#ffffff00",
      "activityBar.background": "#ffffff00",
      "sideBar.border": "#ff0000"
  }
```

it seems the border area there is controlled by `"activityBar.border": "#ff0000"` as using this fills the right border. But that also colors the top of the `activityBar` which may not be desired

**Comment by drcika** [comment]
technically nothing is wrong here
you still have borders, they are just transparent 

it's a matter of personal taste, I want to have it 
I can try to set the border height to 0 if there is no set color

**Comment by drcika** [comment]
more precisely, I will set only sidebar border color on activitybar border-right
unfortunately, I will leave it to the users to add the desired styles themselves, because this cannot be a general solution

**Comment by SilverMarcs** [comment]
Agreed and thanks. Feel free to close the issue when you deem appropriate
