### ISSUE TITLE
How to hide Sidebar title?

### ISSUE THREAD

**Issue by cmaciasjimenez** [drcika/apc-extension#193]
Hello! I'm trying to hide the sidebar title but can't find the answer. I've seen the font size settings but not how to hide it completely.

Could anyone tell me how to achieve it?

![CleanShot 2024-06-07 at 13 21 53@2x](https://github.com/drcika/apc-extension/assets/1439317/2c41b4bb-9dce-4eb1-9fa8-f4dc2cfc9044)

Thank you very much

**Comment by mubaidr** [comment]
```json
"apc.stylesheet": {
  ".monaco-workbench .part > .title > .title-label": "display: none"
}
```

TIP: You can use builtin developer-tools get id/ class of the element you want to customize.
