### ISSUE TITLE
APC Extension Failed

### ISSUE THREAD

**Issue by AlanRMA** [drcika/apc-extension#198]
I'm getting this error every time: 

Apc Extension failed: Error: EROFS: read-only file system, rename '/private/var/folders/5l/6hz20cd564qcslhx7fzw9jbm0000gn/T/AppTranslocation/69D8AF07-F263-4D2D-A3A8-F95A50E9DE6E/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/private/var/folders/5l/6hz20cd564qcslhx7fzw9jbm0000gn/T/AppTranslocation/69D8AF07-F263-4D2D-A3A8-F95A50E9DE6E/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

**Comment by romarmph** [comment]
https://github.com/drcika/apc-extension?tab=readme-ov-file#troubleshooting-extension-issues

**Comment by prasanthkarukkuvel** [comment]
Seems like **bootstrap-amd.js** is not available in VSCode Insiders
