### ISSUE TITLE
`apc.activityBar.position` value support to top

### ISSUE THREAD

**Issue by GXFG** [drcika/apc-extension#2]
```
"apc.activityBar": {
  "position": "bottom" | undefined
}
```

Now `apc.activityBar.position` value only support "bottom" | undefined

**Comment by DeltaRazero** [comment]
On latest stable (1.78.2, entirely fresh install) the top setting is not interactable, meaning that neither the labels/icons are clickable, nor does that the right click menu show up.

**Comment by drcika** [comment]
> On latest stable (1.78.2, entirely fresh install) the top setting is not interactable, meaning that neither the labels/icons are clickable, nor does that the right click menu show up.

update 0.0.8 
execute the command Enable Apc extension
