### ISSUE TITLE
activityBar incomplete when position is top

### ISSUE THREAD

**Issue by biati-digital** [drcika/apc-extension#20]
First of all, Thank you for your work.

When the activityBar is set to top, it does not display all the icons that fit in that space. Setting the position to bottom shows 2 more icons that when set to top.

**Top**
![CleanShot 2023-06-23 at 18 49 14](https://github.com/drcika/apc-extension/assets/1219228/a660262b-bf62-4196-adf8-d1fc7fc280f6)

**Bottom**
![CleanShot 2023-06-23 at 18 49 47](https://github.com/drcika/apc-extension/assets/1219228/fde2a2c5-5ddc-4dc7-8374-b72ce3546c12)

Also the setting trafficLightPosition does not work.

```json
"apc.activityBar": {
    "position": "bottom",
    "hideSettings": true,
    "size": 30,
    "fontSize": 11
  }, 
"apc.statusBar": {
    "position": "editor-bottom",
    "fontSize": 11.5
  },
"apc.electron": {
    "opacity": 1,
    "backgroundColor": "rgba(123, 123, 123, 0)",
    "vibrancy": "sidebar",
    "trafficLightPosition": {
      "x": 17,
      "y": 12
    }
  },
 "apc.listRow": {
    "height": 24,
    "fontSize": 14
  },
 "apc.header": {
    "height": 30
  }
```

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension#apcelectron 
https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions 

"Set a custom position for the traffic light buttons in frameless windows." 
```
 "apc.electron": {
    "titleBarStyle": "hidden", // or "hiddenInset",
    "trafficLightPosition": {
      "x": 17,
      "y": 12
    }
  }
```

**Comment by biati-digital** [comment]
I do not want to set titleBarStyle to hidden, trafficLightPosition should work without modifying the titleBarStyle, check the screenshot, it has a custom trafficLightPosition and the titleBarStyle is not set to hidden or hiddenInset

Anyway, you closed the issue without answering the primary issue i mentioned?

![CleanShot 2023-06-24 at 12 57 51](https://github.com/drcika/apc-extension/assets/1219228/facd548a-981c-4aa2-9c8a-064b72a3a3c8)

**Comment by drcika** [comment]
it's not a issue of this extension nor vscode.

this extension only allows configuring electron / vscode 
I didn't develop anything or provide support for possible bugs
I'm just providing a bridge to configure electron / vscode
all possible configuration

https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions

**Comment by biati-digital** [comment]
Of course is an issue with the extension, I've checked your code. I'll fork it and publish a new version.

**Comment by drcika** [comment]
you have my blessing
