### ISSUE TITLE
Apc Extension failed  in windows

### ISSUE THREAD

**Issue by Ecsilion** [drcika/apc-extension#203]
Apc Extension failed: Error: ENOENT: no such file or directory, rename 'c:\Users\rc7ga\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js' -> 'c:\Users\rc7ga\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js.apc.extension.backup'

**Comment by TakiGuan** [comment]
The same

VS Code Insider latest version
APC extension latest version - v0.3.9

**Comment by ryan6416** [comment]
Facing the same issue in Insiders version:
```
Version: 1.92.0-insider
Commit: b23e791eb5afbd95f05aa24da7693ce89344a079
Date: 2024-07-09T05:03:50.549Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

But it's working in Stable version:
```
Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

cross-post https://github.com/microsoft/vscode/issues/221311

cc: @drcika

**Comment by mubaidr** [comment]
Looks like file has been renamed in newer version. There is no longer `bootstrap-amd.js` in the resources directory. 


```bash
Apc Extension failed: Error: ENOENT: no such file or directory, rename 'c:\Users\USER\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js' -> 'c:\Users\USER\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js.apc.extension.backup'
```

**Comment by Caffeine19** [comment]
i think this would help
![image](https://github.com/drcika/apc-extension/assets/108726581/548ed64a-c234-4847-b0da-a138bcf90a7d)
in src/patch.ts
but havent test yet(not familay with devlop vs code extension)

**Comment by ToddIndry37** [comment]
Got the same issue here. Using VS Code Insiders 1.92.

> Apc Extension failed: Error: ENOENT: no such file or directory, rename ``'c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js'`` -> ``'c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js.apc.extension.backup'``

**Comment by ToddIndry37** [comment]
> i think this would help ![image](https://private-user-images.githubusercontent.com/108726581/347333260-548ed64a-c234-4847-b0da-a138bcf90a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjI0MzEsIm5iZiI6MTcyMDg2MjEzMSwicGF0aCI6Ii8xMDg3MjY1ODEvMzQ3MzMzMjYwLTU0OGVkNjRhLWMyMzQtNDg0Ny1iMGRhLWExMzhiY2Y5MGE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwOTE1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDI4Yzg2YTFhZGI2MjdmZGU4ZmI2MDQzMjU4Nzg1NDIwMDU0OGQ0NDNmM2JjYWFkMDM4YjAyOWZhNWQwYmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GKA4AV2s2uWpB-lhlnrSxX2FV2I9kGimUlXKaa8lUko) in src/patch.ts but havent test yet(not familay with devlop vs code extension)

Where this file located? Was it on VS Code installation folder?

**Comment by Caffeine19** [comment]
> > i think this would help ![image](https://private-user-images.githubusercontent.com/108726581/347333260-548ed64a-c234-4847-b0da-a138bcf90a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjI0MzEsIm5iZiI6MTcyMDg2MjEzMSwicGF0aCI6Ii8xMDg3MjY1ODEvMzQ3MzMzMjYwLTU0OGVkNjRhLWMyMzQtNDg0Ny1iMGRhLWExMzhiY2Y5MGE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwOTE1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDI4Yzg2YTFhZGI2MjdmZGU4ZmI2MDQzMjU4Nzg1NDIwMDU0OGQ0NDNmM2JjYWFkMDM4YjAyOWZhNWQwYmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GKA4AV2s2uWpB-lhlnrSxX2FV2I9kGimUlXKaa8lUko) in src/patch.ts but havent test yet(not familay with devlop vs code extension)
> 
> Where this file located? Was it on VS Code installation folder?

i just clone this repo, modify the source code and build from it, but failed to install on my vscode insiders

**Comment by ToddIndry37** [comment]
Ah, I see. Seem like Microsoft changed the way to do that for APC, I suppose.

**Comment by this-fifo** [comment]
It is not specific to windows, also reported here https://github.com/drcika/apc-extension/issues/198

fwiw — the file does exist on `release/1.91` https://github.com/microsoft/vscode/blob/release/1.91/src/bootstrap-amd.js but I can't see any tags or branches with `1.92.0-insiders`, the file also exists in the latest commit on `main`

**Comment by CentillionJinx** [comment]
What is the possible resolution for this file name change? I tried manually changing the name, but it resulted in more errors, which was expected, since it was a wild attempt.

**Comment by stolinski** [comment]
> What is the possible resolution for this file name change? I tried manually changing the name, but it resulted in more errors, which was expected, since it was a wild attempt.

My understanding is that this extension is broken completely until they issue an update that works with the Insiders build. aka, don't use Insiders or wait for an update.

**Comment by sascharo** [comment]
Still the same issue with 1.92.0-insider and Apc Customize UI++ from 2024-07-29.

**Comment by edgardluz** [comment]
MS pushed this update to mac as well... anyone on a mac that updates VS will get this error and Apc wont work.

**Comment by epulla** [comment]
got the same issue with Mac, I'm using vscode installed via `brew`
