### ISSUE TITLE
Error ENOENT: No such file or directory when enabling APC Customize UI++ on macOS

### ISSUE THREAD

**Issue by prashantkoirala465** [drcika/apc-extension#207]
### Description

When I try to enable the APC Customize UI++ extension on VS Code, I encounter the following error:

Apc Extension failed: Error: ENOENT: no such file or directory, rename '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'

### Screenshot of the issue
<img width="518" alt="Screenshot 2024-08-02 at 10 02 02 AM" src="https://github.com/user-attachments/assets/b30c6acc-2138-4992-95b6-bb75db2a04c0">

**Comment by AninhaPardini** [comment]
Me too! I need help :( My Mac is M1

**Comment by yannxaver** [comment]
Regression after updating vsCode to 1.92

**Comment by NikoMalik** [comment]
same problem after updating vscode "Windows 11"

**Comment by XiaoDaiGua-Ray** [comment]
me too, when update vsc to 1.92!

**Comment by qisthidev** [comment]
there's no file bootstrap-amd.js

**Comment by dasturchioka** [comment]
Same here. There is no file like that in my system (Windows 11 pro, Visual Studio Code v1.92.0)

**Comment by Blankeos** [comment]
Same 🗡️

**Comment by aerscs** [comment]
Same here. Just updated VSC to v1.92

**Comment by macelai** [comment]
Same issue on Mac M1

**Comment by qisthidev** [comment]
Just ran `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup` error message is gone

**Comment by fu050409** [comment]
Same issue on Windows 11

**Comment by Ender-Wang** [comment]
> Just ran `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup` error message is gone

Does apc still work then?

**Comment by NikoMalik** [comment]
> > Just ran `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup` error message is gone
> 
> Does apc still work then?

No

**Comment by pedroalmeida415** [comment]
Welp, tried to brute-force fix it and broke the vscode installation 💀

**Comment by fu050409** [comment]
> Welp, tried to brute-force fix it and broke the vscode installation 💀

Ahh, what a pity, maybe you have to reinstall it

**Comment by fu050409** [comment]
> Just ran `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup` error message is gone

Infact, it's true that no more exceptions popped up anymore after actually executing this command manually, but unfortunately, my apc failed to work just as well, and it didn't do anything substantial (i customized my vscode to make it transparent).

**Comment by qisthidev** [comment]
> Just ran `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup` error message is gone

that's odd, mine is still working properly

<img width="1682" alt="image" src="https://github.com/user-attachments/assets/248bf10c-b16a-451c-aa7d-676048ed81e8">

using latest stable with that trick

<img width="1682" alt="image" src="https://github.com/user-attachments/assets/76e433e8-11fd-4761-8981-c631c869f411">

**Comment by fu050409** [comment]
@ramaID Ahh? That's very odd, could you please list the files under `resources\app\out`? I have executed `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup`. I don't know if our differences are due to the fact that I'm on Windows ？

Mine:

```console
resources\app\out via  v21.6.1
❯ ls

    Directory: C:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            2024/8/2    10:52                vs
d----            2024/8/2    10:52                vscode-dts
-a---            2024/8/1     0:12          48868 bootstrap-amd.js.apc.extension.backup
-a---            2024/8/1     0:12          48868 bootstrap-fork.js
-a---            2024/8/1     0:12          49534 cli.js
-a---            2024/8/1     0:12          61286 main.js
-a---            2024/8/1     0:12         394063 nls.keys.json
-a---            2024/8/1     0:12         634362 nls.messages.json
```

**Comment by prashantkoirala465** [comment]
# Issue Report: APC Customize UI++ Extension Compatibility - Fixed

## Problem

The APC Customize UI++ extension is currently broken and not compatible with the latest version of Visual Studio Code (VS Code). Users have reported functionality issues following recent updates to VS Code.

## Solution

The issue can be resolved by downgrading VS Code to the previous version (1.91). Here’s a step-by-step guide on how to do this depending on your installation method:

### Manual Installation (Browser Download)

1. **Download VS Code 1.91:**
   - Download the previous major version (1.91) from [here](https://code.visualstudio.com/updates/v1_91)
   - Overwrite your current installation. Your extensions and settings will be preserved.

2. **Update Settings:**
   - After downgrading, go to Preferences.
   - Search for 'Update'.
   - Set `Update: Mode` to `none`.
   - or you can add these lines to your settings.json file:
   
   
<img width="1027" alt="Screenshot 2024-08-02 at 10 13 45 PM" src="https://github.com/user-attachments/assets/e4e92f78-c483-4e1c-abd1-b2231d5f2161">

### Homebrew Installation (macOS)

1. **Install VS Code 1.91.1:**
   - Run the command:
     ```bash
     brew install visual-studio-code@1.91.1
     ```

2. **Download and Install Cask File:**
   - Download the 1.91.1 cask file from [here](https://github.com/Homebrew/homebrew-cask/blob/506e9abc71c30c294d4dfb139245646060f89a3e/Casks/v/visual-studio-code.rb).
   - Navigate to the folder where the file was downloaded.
   - Install using:
     ```bash
     brew install --cask ./visual-studio-code.rb
     ```

### Linux Microsoft Repo Installation

1. **Downgrade VS Code:**
   - Run the following commands:
     ```bash
     sudo apt remove code
     sudo apt autoremove
     sudo apt install code=1.91.1
     ```

2. **Update Settings:**
   - After downgrading, go to Preferences.
   - Search for 'Update'.
   - Set `Update: Mode` to `none`.
   
   or you can add these lines to your settings.json file:
   
   
<img width="1027" alt="Screenshot 2024-08-02 at 10 13 45 PM" src="https://github.com/user-attachments/assets/e4e92f78-c483-4e1c-abd1-b2231d5f2161">


## Note

After downgrading to VS Code 1.91, GitHub Copilot Chat may not function correctly and might prompt for a newer version of VS Code. 

<img width="951" alt="Screenshot 2024-08-02 at 10 15 10 PM" src="https://github.com/user-attachments/assets/22d2c233-9f7c-4bc8-834d-05732c65801c">


However, the APC Customize UI++ extension and other functionalities work fine.



## Screenshot 

![Fixed Issue](#)  
<img width="1440" alt="Screenshot 2024-08-02 at 10 16 24 PM" src="https://github.com/user-attachments/assets/166c9109-602a-48ba-b8dc-1ac6d53810a2">


## Credits

This solution was adapted from the GitHub issue report [here](https://github.com/drcika/apc-extension/issues/206). @steveulfelder

For further assistance, please refer to the issue page or reach out to the community for support.

**Comment by qisthidev** [comment]
> @ramaID Ahh? That's very odd, could you please list the files under `resources\app\out`? I have executed `cp bootstrap-fork.js bootstrap-amd.js.apc.extension.backup`. I don't know if our differences are due to the fact that I'm on Windows ？
> 
> Mine:
> 
> ```
> resources\app\out via  v21.6.1
> ❯ ls
> 
>     Directory: C:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d----            2024/8/2    10:52                vs
> d----            2024/8/2    10:52                vscode-dts
> -a---            2024/8/1     0:12          48868 bootstrap-amd.js.apc.extension.backup
> -a---            2024/8/1     0:12          48868 bootstrap-fork.js
> -a---            2024/8/1     0:12          49534 cli.js
> -a---            2024/8/1     0:12          61286 main.js
> -a---            2024/8/1     0:12         394063 nls.keys.json
> -a---            2024/8/1     0:12         634362 nls.messages.json
> ```

```
..p/Contents/Resources/app/out❯ ls -al
total 2432
drwxr-xr-x@ 10 rama  admin     320 Aug  2 21:10 .
drwxr-xr-x@ 14 rama  admin     448 Aug  1 14:13 ..
-rw-r--r--@  1 rama  admin   48868 Aug  2 21:10 bootstrap-amd.js.apc.extension.backup
-rw-r--r--@  1 rama  admin   48868 Aug  1 13:25 bootstrap-fork.js
-rw-r--r--@  1 rama  admin   49534 Aug  1 13:25 cli.js
-rw-r--r--@  1 rama  admin   61286 Aug  1 13:25 main.js
-rw-r--r--@  1 rama  admin  394063 Aug  1 14:03 nls.keys.json
-rw-r--r--@  1 rama  admin  634362 Aug  1 14:03 nls.messages.json
drwxr-xr-x@  7 rama  admin     224 Aug  1 14:13 vs
drwxr-xr-x@  3 rama  admin      96 Aug  1 14:13 vscode-dts
```

**Comment by prashantkoirala465** [comment]
> Me too! I need help :( My Mac is M1
you can refer to this fix I just posted: [here](https://github.com/drcika/apc-extension/issues/207#issuecomment-2265760157)

**Comment by fu050409** [comment]
@ramaID Thanks for your extra information, but it failed to work for me here. It seems to be a very metaphysical problem 😒, so I'll just decide to downgrade my vscode for now and wait for the community to give further solutions.

**Comment by pedroalmeida415** [comment]
### Okay so, I did some digging and... its bad news

Basically, all the modules that APC tweaked into VSCode's config are now gone, along with the files that were used as entry point to patch the `require()` calls of said modules.

The silver lining here could be that this actually makes it easier to do those patches and restore functionality, but I can't really claim that and even so, most likely, the extension will still need to be completely refactored as to how it is implemented today.

**Edit**: Glad it wasn't that bad of a fix, it now works as of version 4.0 🎉

**Comment by dir** [comment]
F

**Comment by rrooddooxx** [comment]
why Microsoft constantly does this? on every customize UI extension for VSCode I've used....

**Comment by steveulfelder** [comment]
@alexbytesback the paste is incorrect. homebrew reinstall has only 3 steps, the first section (`brew install visual-studio-code@1.91.1`) was struck out because it does not work.

**Comment by bladezcode** [comment]
still not working on 0.4.1 apc extension

**Comment by fu050409** [comment]
> still not working on 0.4.1 apc extension 

@bladezcode What happened? Have you upgraded your vscode to the latest version?

**Comment by bladezcode** [comment]
> > still not working on 0.4.1 apc extension 
> 
> @bladezcode What happened? Have you upgraded your vscode to the latest version?


yep im just using apc to remove the title bar but it doesn't work on latest vscode. tried clearing cache and restarting multiple times to no avail

**Comment by fu050409** [comment]
@bladezcode Have your tried other features? For example, config a transparent background, which works properly on my vscode. If this doesnt work, maybe you should try to reinstall your vscode. If this worked, and your config working in previous version of vscode, maybe this is a new issue.

**Comment by dasturchioka** [comment]
@alexbytesback I did downgrade the vscode into 1.91.0 and now my extension market is not working.

![image](https://github.com/user-attachments/assets/d43ec96a-54dd-4ff3-b4f3-cf4c5577f59f)

When I need new extensions to download, it doesn't show me any suggestions from the marketplace

**Comment by forivall** [comment]
> why Microsoft constantly does this? on every customize UI extension for VSCode I've used....

Looks like they're going to be doing more work which will likely break apc. Hopefully once they finish the switch to esm, then things should settle down:

https://code.visualstudio.com/updates/v1_92#_progress-on-using-esm-for-vs-code
> In this milestone, we picked up the work again to adopt ESM for VS Code core. Our goal in the future is to use ECMAScript Modules (ESM) loading and drop AMD entirely. This is a multi-milestone effort that will modernize overall code loading and bundling.
