### ISSUE TITLE
Position control for activity Bar does not work

### ISSUE THREAD

**Issue by German-Sagal** [drcika/apc-extension#208]
The "position": "top" setting for activityBar stopped working

    "apc.activityBar": {
      "position": "top",
      "hideSettings": true,
      "itemMargin": 3,
      "itemSize": 36,
      "size": 35
    },

**Comment by rez1-dev** [comment]
Yeah, vscode integrated it. Read this section
https://github.com/drcika/apc-extension?tab=readme-ov-file#apcactivitybar

**Comment by rez1-dev** [comment]
`"hideSettings": true,` is removed in later versions.
