### ISSUE TITLE
[Bug] An "undefined" tab

### ISSUE THREAD

**Issue by SavedRest0Re** [drcika/apc-extension#21]
<img width="1301" alt="bu1" src="https://github.com/drcika/apc-extension/assets/8685050/098d6957-a443-41c3-b266-9a32e2e3c5eb">

Here is my configuration:
```json
"apc.header": {
    "height": 28,
},
"apc.activityBar": {
    "position": "top",
    "size": 34,
},
```

## How to reproduce
Step1: Close all the open files.
<img width="1544" alt="bug3" src="https://github.com/drcika/apc-extension/assets/8685050/c290f4ef-22d8-4711-8820-9def53d44367">

Step2: Then, just open any file or create a new file. 
You will get:
<img width="1544" alt="bug4" src="https://github.com/drcika/apc-extension/assets/8685050/eab2dbba-369d-4336-946d-e80325869dfd">

Repeating the above steps, will get more "undefinde".

**Comment by drcika** [comment]
can't reproduce
![Screenshot 2023-06-26 at 12 32 50](https://github.com/drcika/apc-extension/assets/35919606/a9919df3-939f-4302-80e4-04c1ea1ba7b6)

can you open the developer tools? 
Is there any error?
