### ISSUE TITLE
Latest version frame false invalid

### ISSUE THREAD

**Issue by alaric8** [drcika/apc-extension#216]
Latest version frame false invalid

版本: 1.92.2 (user setup)
提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
日期: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by rez1-dev** [comment]
You can use default settings to hide window controls.

**Comment by alaric8** [comment]
![image](https://github.com/user-attachments/assets/f05ed2a3-f504-4052-abd3-7486460fb7ae)
I want to achieve this effect

**Comment by alaric8** [comment]
![image](https://github.com/user-attachments/assets/03600aed-0cc1-48b6-a145-9e008ab83277)

**Comment by lethefrost** [comment]
> You can use default settings to hide window controls.

Sorry for disturbing, do you mind explaining a little more details? Which settings are involved and what values should they be set to?

**Comment by rez1-dev** [comment]
@lethefrost The downside of using `frame` on Windows OS is: you can't drag vscode while holding title bar.

Just for hiding window controls, I use
```json
    "window.menuBarVisibility": "compact",
    "window.commandCenter": false,
    "workbench.layoutControl.enabled": false,
    "workbench.editor.showTabs": "single",
```

**Comment by lethefrost** [comment]
> @lethefrost The downside of using `frame` on Windows OS is: you can't drag vscode while holding title bar.
> 
> Just for hiding window controls, I use
> 
> ```json
>     "window.menuBarVisibility": "compact",
>     "window.commandCenter": false,
>     "workbench.layoutControl.enabled": false,
>     "workbench.editor.showTabs": "single",
> ```

Thanks!

**Comment by alaric8** [comment]
"apc.electron": {
        "frame": false,
    },
    "apc.menubar.compact": true,
    "apc.listRow": {
        "fontSize": 18,
        "height": 25,
        "lists": [
            "customview-tree",
            "results",
            "open-editors",
            "explorer-folders-view",
            "outline-tree",
            "scm-view",
            "debug-view-content",
            "debug-breakpoints",
           "tree"
        ],
        "parts": {}
    },  

I reopened it and it worked again. I don't know the problem. I kept restarting it and it didn't work before.
![image](https://github.com/user-attachments/assets/86c259ba-697a-4fc9-bb8f-815ef2954646)
The effect I want to achieve is as shown above.

**Comment by alaric8** [comment]
This extension is gone, but it works again.
![image](https://github.com/user-attachments/assets/c77aebd2-1e2f-413a-9678-df9e390393d9)

**Comment by alaric8** [comment]
![image](https://github.com/user-attachments/assets/e2873b4d-8da4-44c8-9d26-a5834a81ecf3)
After restarting the system, it has no effect
