### ISSUE TITLE
How to change UI font?

### ISSUE THREAD

**Issue by Derpitron** [drcika/apc-extension#22]
I am inexperienced with CSS and Electron. I would like some hand-holding instructions on how to change the Fonts from the System Font to my own custom Font:
![image](https://github.com/drcika/apc-extension/assets/46134462/06506967-1251-4f0e-923f-7e1651c5139e)

**Comment by drcika** [comment]
you must have the font installed 
or import
```
  "apc.imports": [
    {
      "rel": "stylesheet",
      "href": "https://fonts.googleapis.com/css?family=Sofia"
    }
  ],
``` 
then overwrite default font Family 
note* the spaced font must be in quotation marks 
"Inter Display" - wrong
"'Inter Display'" - correct
```
  "terminal.integrated.fontFamily": "Sofia",
  "editor.fontFamily": "Sofia",
  "apc.stylesheet": {
    "*": "font-family: 'Sofia'", // "*" means everything
    // specific parts
    ".sidebar *": "font-family: 'Sofia'",
    ".auxiliarybar *": "font-family: 'Sofia'",
    ".panel *": "font-family: 'Sofia'",
    ".tabs *": "font-family: 'Sofia'",
    ".statusbar *": "font-family: 'Sofia'",
  }
```
or open the dev tool 
find the appropriate class 
and apply the style
![Screenshot 2023-06-26 at 18 45 36](https://github.com/drcika/apc-extension/assets/35919606/d96efaee-c3f6-410f-b8ba-f760f9522284)
![Screenshot 2023-06-26 at 18 46 41](https://github.com/drcika/apc-extension/assets/35919606/898d35ed-79ce-4163-8102-6297971f728e)

**Comment by Derpitron** [comment]
Thank you. This worked for me!
![image](https://github.com/drcika/apc-extension/assets/46134462/eb7e5365-5345-42f3-a9ed-0b776389760f)

**Comment by Derpitron** [comment]
How can I change the value of `--vscode-font-family` Style variable?
![image](https://github.com/drcika/apc-extension/assets/46134462/fbb6feaf-5c6b-4361-8089-2c275d216d07)

![image](https://github.com/drcika/apc-extension/assets/46134462/ee3fda9b-5a1c-4de3-ac52-0fd2f9456874)
This is my current config which does not work.

**Comment by drcika** [comment]
vscode do not have set inline font 
![Screenshot 2023-06-27 at 08 15 54](https://github.com/drcika/apc-extension/assets/35919606/3e0e2a33-f380-4bd2-8304-458e2f0285b9)

you need js to rewrite inline style

```
"apc.imports": [ "file:///C:/path/to/script.js" ]
```
script.js 
```
document.querySelector('html').style.setProperty('--my-var', 'my value')
```

**Comment by Derpitron** [comment]
Thank you!

**Comment by neinnew** [comment]
Is there a way to change the font on the extension page? I tried the above method, but it becomes a cross-origin script so I can't access it.

![화면 캡처 2023-06-30 154619](https://github.com/drcika/apc-extension/assets/44744452/01826de4-cf47-4a51-bebe-bb44d5985c0a)

**Comment by drcika** [comment]
it is "iframe"
and pull data directly from the marketplace

it is probably possible
but you need complex logic in a custom script to track if you are on that part and when you catch insert styles

when I have time I will see if I can make that process easier

now you can the part that isn't iframe
```
".extension-editor *": "font-family: 'Sofia'",
```

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension#fontfamily

**Comment by Derpitron** [comment]
You are a powerhouse of a maintainer. Bless you!

**Comment by Derpitron** [comment]
![image](https://github.com/drcika/apc-extension/assets/46134462/38cfeb69-eb24-4f0c-aa0f-7dcaf3cc2d70)
How can I change the UI font-family using `apc.font.family`? The setting shown in this picture does not work.

**Comment by drcika** [comment]
Try without '
"Inter Display"

**Comment by Derpitron** [comment]
Still does not work

**Comment by yuuuxt** [comment]
Seems the right-click context menu doesn't apply the specified font? I was using [fonted](https://github.com/blackmann/fonted) and want to switch to apc for the font part. Thanks for the work!

**Comment by neinnew** [comment]
@yuuuxt  It works for right-click context menu
```
"apc.stylesheet": {
    ".shadow-root-host ": "font-family: '\\\\\\\' ",
  },
```

**Comment by yuuuxt** [comment]
> @yuuuxt It works for right-click context menu
> 
> ```
> "apc.stylesheet": {
>     ".shadow-root-host ": "font-family: '\\\\\\\' ",
>   },
> ```

Confirmed it works, 

meanwhile for me as I'm using windows and want to use `native` title bar style to hide the title bar, the context menu follows to be native and the style no longer applies. I decide to keep title bar hidden for now :)

![image](https://github.com/drcika/apc-extension/assets/3153534/77f6a20f-a72a-45c3-847e-88772c20785a)

**Comment by drcika** [comment]
everything I found I override (on macos) 
some things in some cases are native (change system font :D)
If someone finds an additional solution 
submit PR or let me know about it and I will add it

**Comment by Derpitron** [comment]
> Still does not work

Hey @drcika , any solution for this ?

**Comment by drcika** [comment]
I don't know what to tell you without details, I can't help you

do you have the font installed on your computer??
do you regularly upgrade to the latest version??

try this example
```
  "apc.imports": [
      {
        "rel": "stylesheet",
        "href": "https://fonts.googleapis.com/css?family=Sofia"
      },
  ],

  "apc.font.family": "Sofia", 
```
it should work

![Screenshot 2023-07-07 at 17 46 28](https://github.com/drcika/apc-extension/assets/35919606/1ca13f6b-b6ce-47bb-b331-b894d30a49e6)

**Comment by Derpitron** [comment]
> I don't know what to tell you without details, I can't help you
> 
> do you have the font installed on your computer?? do you regularly upgrade to the latest version??
> 
> try this example
> 
> ```
>   "apc.imports": [
>       {
>         "rel": "stylesheet",
>         "href": "https://fonts.googleapis.com/css?family=Sofia"
>       },
>   ],
> 
>   "apc.font.family": "Sofia", 
> ```
> 
> it should work
> 
> ![Screenshot 2023-07-07 at 17 46 28](https://user-images.githubusercontent.com/35919606/251792611-1ca13f6b-b6ce-47bb-b331-b894d30a49e6.png)

I have the font family installed on my system. I will try this example myself

**Comment by mon-jai** [comment]
@dicka Is it possible to use web font in iframe?

**Comment by drcika** [comment]
unfortunately no, only system font

**Comment by mon-jai** [comment]
It seems that defining `@font-face` in "apc.iframe.style" doesn't work, even with data url (`src: url("data:font/ttf;base64,...");`).

Is that a bug or a limitation?

**Comment by drcika** [comment]
Limitation
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by lakshits11** [comment]
Hi, I am using following settings still I am shown Segoe UI font in ipynb notebook markup:
```json
"apc.stylesheet": {
        "*": {
            "-webkit-text-stroke-width": "0.3px"
        }
 },
"apc.font.family": "Inter",
"apc.monospace.font.family": "SF Mono",
```

Still:

![image](https://github.com/drcika/apc-extension/assets/54276661/4ba187d6-ac16-4ed6-962d-9cdaa3b2e800)


You can see, this segoe ui font is not chaning, other settings are changed. Please help.
