### ISSUE TITLE
Inline Titlebar hides titlebar but disables buttons

### ISSUE THREAD

**Issue by ghost** [drcika/apc-extension#24]
When the `inline titlebar` setting is enabled, the title bar gets hidden, and the tab bar becomes draggable.

However, there is a bug related to the functionality of the buttons on the title bar. Only the **Close button** is functional, while the other three buttons, namely:

- Open settings (UI)
- Split editor right
- More actions

do not respond to clicks.

EDIT
On **Windows** machine, same thing occurs in `EXPLORER` panel.

To provide a clear understanding of the problem, I have attached a video demonstrating the bug.

https://github.com/drcika/apc-extension/assets/84121715/498cccd9-a8d0-499f-b1a0-5e3ba8efedbf

**Comment by ghost** [comment]
@drcika, can you confirm if the buttons in the `EXPLORER` panel are functioning correctly on your end? Or are they hidden?

**Comment by drcika** [comment]
a little strange bug, only on windows

**Comment by ghost** [comment]
Can you kindly fix the same issue for the remaining panels too?
Such as `EXPLORER`, `EXTENSIONS`, `Run and Debug` and `Source Control`.

**Comment by ghost** [comment]
@drcika Thank you so much! All of my problems have been completely sorted out.
