### ISSUE TITLE
Request for Logo Addition and Logo Design Suggestions

### ISSUE THREAD

**Issue by ghost** [drcika/apc-extension#26]
It would greatly enhance the overall appearance and branding of this extension to have a distinctive logo.

I have some logo design suggestions that I would like to propose. You can choose any of them.

![1](https://github.com/drcika/apc-extension/assets/84121715/26c5fd30-fc92-44a1-afb2-ae68016e0b68) ![2](https://github.com/drcika/apc-extension/assets/84121715/5fd0b824-4a7c-4028-9e22-34001c7af8c9) ![3](https://github.com/drcika/apc-extension/assets/84121715/b902dcb4-3724-4570-844f-c5c65db23b81) ![4](https://github.com/drcika/apc-extension/assets/84121715/235cb65d-ec0d-481b-9e6b-f773be3ea147) ![5](https://github.com/drcika/apc-extension/assets/84121715/0bbf967c-54f8-4c14-9af1-9e4a40ce21e5) ![6](https://github.com/drcika/apc-extension/assets/84121715/be2f1291-d855-4548-9531-68fb1b9b6e10) ![7](https://github.com/drcika/apc-extension/assets/84121715/ee261419-4042-42bd-b563-6713f3742316) ![8](https://github.com/drcika/apc-extension/assets/84121715/726b1594-303b-4bc0-a9a6-8c6a77b1577d) ![9](https://github.com/drcika/apc-extension/assets/84121715/97db1173-7e47-420c-86cc-6d0eac675aad)

If you're not satisfied with any of the options, let me know which one(s) you would like me to edit or modify.
And I'll be happy to make the necessary changes.

**Comment by drcika** [comment]
choose freely, I'm not for design, I'm an engineer :D

**Comment by ghost** [comment]
IMO, first one would be nice.

**Comment by ghost** [comment]
@drcika Once you have completed a fresh release, it is important to ensure that the `CHANGELOG.md` is updated accordingly.
