### ISSUE TITLE
Feature Request: Custom Style for Notebooks

### ISSUE THREAD

**Issue by yuuuxt** [drcika/apc-extension#29]
I use [jupyter notebook](https://github.com/microsoft/vscode-jupyter/) in vscode, and seeing the font setting also applies to font for notebooks is awesome (I didn't find a way to do that)!

(I'm not sure if it's already possible, but) It would be good to provide some setting options or guides to further customize the look of notebooks. E.g., what I want to change most is to make the markdown headers bold and numbered.

Thanks for the great work!

**Comment by drcika** [comment]
Open dev tool 
Find desired element/part 
apply the style 

```
  "apc.imports": [ "/path/to/style.css" ]
``` 
or 

```
  "apc.stylesheet": {
    ".notebook-editor .mtk1": "font-weight: bold; color: red"
    }
```

<img width="1788" alt="Screenshot 2023-07-01 at 21 19 21" src="https://github.com/drcika/apc-extension/assets/35919606/1325a537-116b-48fc-b236-74d2ddf55719">

**Comment by yuuuxt** [comment]
while your example works as expected, the exact example doesn't work (also why I was stuck): 

the cell needs to be markdown and needs to be rendered (before/after rendering):
![image](https://github.com/drcika/apc-extension/assets/3153534/10fb5837-2fec-471b-8dd9-14c28f0df0cb)
![image](https://github.com/drcika/apc-extension/assets/3153534/84d68ef0-eafc-4631-b982-4b0e44190bf6)

- before rendering it's similar except that it's `mtk11` and it's working;
- after rendering it's like this, and the selectors there seems not working.
![image](https://github.com/drcika/apc-extension/assets/3153534/9a1a53eb-fae3-4bef-952d-b0bfe3842213)

Could you help give some hints?

**Comment by drcika** [comment]
sorry never used notebook 
after "render" becomes iframe 
unfortunately, until I find a suitable way to insert styles inside iframes, customization  is not possible

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension#apciframestyle 

```
"apc.iframe.style": "/Users/path/style.css",
```
```
h1 {
  color: red
}
```

only applies inside iframes
but also on all iframes such as extension view
keep that in mind when writing styles

**Comment by yuuuxt** [comment]
Looks nice and will try it out! 
One more question: is it possible to directly write styles in `settings.json`, just like `apc.stylesheet`?

**Comment by drcika** [comment]
it complicates things a lot, and settings.json is already too bulky 
I follow the changes in the custom file, it is only necessary to open the tab again

**Comment by yuuuxt** [comment]
seems I failed to make it running:
- extension `v0.2.3`,
- created a file as the example above and saved to (win10) `D:\vscode_notebook.css`,
- added setting of `"apc.iframe.style":"/D:/vscode_notebook.css",`
- reopening notebook tab and the `h1` rendered title doesn't change.

**Comment by drcika** [comment]
somehow they managed to protect themselves on windows, it should work now 
but it has a small limitation 
if a tab with an iframe is open when starting vscode, the tab needs to be reopened for the styles to apply

**Comment by airtonix** [comment]
doesn't seem to be working anymore
