### ISSUE TITLE
`trafficLightPosition` is ignored when `window.titleBarStyle` is `custom`

### ISSUE THREAD

**Issue by giovanicascaes** [drcika/apc-extension#33]
I'm setting the `trafficLightPosition` config, but there is no effect:

<img width="621" alt="image" src="https://github.com/drcika/apc-extension/assets/3672165/2770567a-10de-4091-a681-906b3a6720ec">

```json
"apc.electron": {
    "trafficLightPosition": {
      "x": 5,
      "y": 7
    }
  },
```

I want to position the traffic lights, but also want the title bar, command center and buttons

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension#%EF%B8%8Fdisclaimer
https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions

"trafficLightPosition (optional) macOS - Set a custom position for the traffic light buttons in frameless windows."
