### ISSUE TITLE
Feature request: Allow for apc.header.height to be 0

### ISSUE THREAD

**Issue by WesselvanGils** [drcika/apc-extension#36]
Currently the smallest setting is 1. 
Being able to completely hide the tab and breadcrumbs bar would be nice. There already is an [issue](https://github.com/microsoft/vscode/issues/33607) about this in the vscode repo but the devs there don't seem to want to implement it as stated in this [pull request](https://github.com/microsoft/vscode/pull/70140).

**Comment by drcika** [comment]
have you tried? 
```
  "apc.header": {
     "height": 0.0000001,
  },
    "apc.stylesheet": {
       ".tabs": {
         "opacity": 0,
      }
  },
``` 
complete removal would cause a number of other problems, probably that's why they won't implement it, the bottom line header must be there and have some height 

they have made a lot of mistakes in the past when it comes to solving some problems, they put fixed sizes in a lot of places, and a change like this would bring down a lot of things like a house of cards

**Comment by WesselvanGils** [comment]
This works like a charm, thanks!

**Comment by WesselvanGils** [comment]
Though this does happen at the bottem of the page
![image](https://github.com/drcika/apc-extension/assets/60363527/12848aed-453c-486c-aa4e-1922de21a67a)

The scroll bar also seems to sit on top of this. Some more styling is needed so that the editor takes up the full height. In the vscode issue someone managed this by doing

```
/* ## Force the editor area to use full height. */
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs>div.lines-content.monaco-editor-background>div.view-lines.monaco-mouse-cursor-text {
    height: 100% !important;
}
```
 But I'm unsure of how to do this using APC
