### ISSUE TITLE
[Request] Publish instructions on how to install and use

### ISSUE THREAD

**Issue by Derpitron** [drcika/apc-extension#4]
I am quite confused on how to install and use this extension. Does it require monkeypatch to be installed? Can it be installed like a normal extension?

**Comment by drcika** [comment]
Just install, and configure as you like
https://github.com/drcika/apc-extension/blob/production/demo/settings.json
the extension comes with no default settings

**Comment by robsontenorio** [comment]
@Derpitron you should uninstall Monkey Patch and Custom UI extensions. Reopen VSCODE. 

Then install APC like a normal extension. 

So you go to `settings.json` to apply your customization.
