### ISSUE TITLE
Keybindings list row height should not be overridden

### ISSUE THREAD

**Issue by forivall** [drcika/apc-extension#41]
custom list row off:
<img width="676" alt="Screenshot 2023-07-06 at 12 47 21 PM" src="https://github.com/drcika/apc-extension/assets/760204/c859962a-6a84-4339-b1d6-03438534aae9">
custom list row on:
<img width="666" alt="Screenshot 2023-07-06 at 12 47 38 PM" src="https://github.com/drcika/apc-extension/assets/760204/f2d043d6-e366-4efb-90ee-a9a677369bd3">

**Comment by drcika** [comment]
how to reproduce? 
settings.json etc 

![Screenshot 2023-07-07 at 05 55 58](https://github.com/drcika/apc-extension/assets/35919606/08d1a510-bfb6-4083-9fb8-0225f88b177b)

**Comment by vfa-trungnm** [comment]
> how to reproduce? settings.json etc

@drcika
I have same problem. Type to search, don't just open it.
Please fix it.
![image](https://github.com/drcika/apc-extension/assets/49382720/7a6233eb-61f9-4d90-95fb-08eb20283357)

**Comment by vfa-trungnm** [comment]
@drcika why do you close this issue?

**Comment by vfa-trungnm** [comment]
@drcika thank you
