### ISSUE TITLE
Would it be within the scope of this extension to move the find widget to the bottom?

### ISSUE THREAD

**Issue by videopilot** [drcika/apc-extension#44]
Sublime and Atom both have a similar find widget, but theirs comes up at the bottom of the editor and is full width. With the old customize UI, I got vscode to do this with css, but it required setting the editor to scroll past the last line, which I'd prefer not to do.

Would it make sense to have this extension optionally relocate the find widget to the bottom of the editor and have it resize the editor so that it doesn't cut off the bottom of the file?

<img width="500" alt="image" src="https://github.com/drcika/apc-extension/assets/6528746/baa95d6c-6f5a-442f-a746-56ab710ad052">

<img width="500" alt="Screenshot 2023-07-07 at 2 28 53 AM" src="https://github.com/drcika/apc-extension/assets/6528746/f447134a-81d2-4457-9e6d-d95623e0c2e9">

<img width="500" alt="Screenshot 2023-07-07 at 2 29 33 AM" src="https://github.com/drcika/apc-extension/assets/6528746/521e3502-9963-4ef3-90dc-f9fad4418b53">

**Comment by drcika** [comment]
you can achieve that with custom styles, just play around
```
  "apc.stylesheet": {
    ".monaco-editor .find-widget.visible": {
      "position": "fixed !important",
      "top": "unset !important",
      "bottom": "50px"
    }
  },
```
what you want requires a lot of work, and thus increases the room for mistakes, primarily because the vscode team implemented it the way it did, maybe it's better to contact them
