### ISSUE TITLE
Seems to be not working, in VSCode 1.80.0 (updated on 2023-07-04).

### ISSUE THREAD

**Issue by maskzh** [drcika/apc-extension#45]
Thank you for amazing work, it looks great. but it stopped working after the update at 1.80.0.

**Comment by drcika** [comment]
I don't know what to tell you, without details I can't help you
I checked all latest versions

- vscode 1.81.0 - win and macos
- vscode 1.81.1-insider - win and macos
- vscodium 1.79.2 - win and macos

and everything works fine

the only thing I can tell you now is to try to reenable it
Go to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
Type "Enable Apc extension" and enter to enable the extension.

**Comment by maskzh** [comment]
Sorry, I had thought this was a commonly occurring issue, so I didn’t provide any information.

> Type "Enable Apc extension" and enter to enable the extension.

I try to reenable it, and it works now.

Thank you for you reply. 🌷

There may be a little confusion here, after upgrading VSCode, you need to manually enable it.

**Comment by drcika** [comment]
it should be done automatically, I don't know why it isn't now
