### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by stemcc** [drcika/apc-extension#49]
Attempting to use this extension running Fedora 38 results in the following error:

`Apc Extension failed: Error: EACCES: permission denied, rename '/usr/share/code/resources/app/out/bootstrap-amd.js' -> '/usr/share/code/resources/app/out/bootstrap-amd.js.apc.extension.backup'`

**Comment by drcika** [comment]
it needs permission to be able to modify itself
https://github.com/drcika/apc-extension#mac-and-linux-users 

- enable permission
- reenable extension (execute command "Enable Apc extension" from command Palette)

**Comment by HeyProtagonist** [comment]
@drcika
This is a bit manual, Perhaps you can enable it by default when the dev installs the extension or is this the behaviour you wanted..?

**Comment by drcika** [comment]
system security issue

**Comment by stemcc** [comment]
Since there’s no way for me to enable those permissions on my system by a prompt from vscode, what simply works is taking ownership of the `usr/share/code/resources/app/out` folder after each vscode update.

**Comment by camilo-colon** [comment]
The solution on Mac is to move the visual studio application to the application folder, by default visual studio is downloaded and executed from download. In my case I just moved visual studio code from downloads to the application folder and everything worked correctly.

**Comment by Geisson19** [comment]
In Ubuntu, I ran `sudo chown -R $(whoami) /usr/share/code`, and it resolved the issue.
