### ISSUE TITLE
Support equivalent of "customizeUI.activityBar": "wide"

### ISSUE THREAD

**Issue by lehni** [drcika/apc-extension#52]
First of all, thank you for making this great extension! I'm the author of the original [vscode-titlebar-less-macos](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos), which I discontinued when the great [Customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) by @iocave came long, and in the past months I have been maintaining a custom version of it that would keep working on VSCodium, as the only viable solution to still get my desired UX layout:

https://github.com/iocave/customize-ui/issues/156#issuecomment-1411197296
https://github.com/iocave/customize-ui/issues/170#issuecomment-1503371606

<img width="1149" alt="Screenshot 2023-07-16 at 12 21 29" src="https://github.com/drcika/apc-extension/assets/213275/3c5e6628-ff6f-4c9e-800f-ab4b8ddeceaf">

But your APC extension has come to rescue and really looks like a solid path forward!

The only bit missing for me right now is the style where the activity bar will match the width of the traffic lights for macOS inline menu bar, and align the activity bar items underneath, as shown in the screenshot above.

After a lot of fiddling around with the settings, I have managed to achieve this look with APC using some custom CSS, but I need to undo a lot of APC's `.activitybar` styling that affects position and sizing of the action items, and I'm hoping there will be a better way to achieve this more easily.

Also, I don't think APC should hide the host button in the bottom left corner by default. It could expose this through an option? I can create a second issue for that.

My current settings are:

```jsonc
{
    "window.titleBarStyle": "native",
    "apc.electron": {
        "titleBarStyle": "hiddenInset",
    },
    "apc.header": {
      "height": 37
    },
    "apc.sidebar.titlebar": {
      "height": 37
    },
    "apc.activityBar": {
        "size": 77
    },
    "apc.stylesheet": {
        ".custom-sidebar-titlebar .sidebar .composite.title": "padding-left: 0;",
        // Make room for the traffic lights.
        ".custom-activitybar div.monaco-workbench div.activitybar > div.content": "margin-top: var(--titlebar-height);",
        // Reset strange APC .activitybar styling back to VSCode defaults.
        ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item": "margin-top: 0 !important;",
        ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item a.action-label": "width: 48px; height: 48px; font-size: 24px; margin: 0 auto; -webkit-mask-size: 1em;",
        ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item .badge div.badge-content": "top: 24px; right: 8px;",
        // Don't indent the statusbar items.
        ".monaco-workbench .part.statusbar>.items-container>.statusbar-item.left.first-visible-item": "padding-left: 0;",
        // Show the host button again, and make it as wide as the .activitybar.
        ".statusbar #status\\.host": "display: block !important; width: calc(var(--activity-bar-action-size) - 1px); background: #555 !important;",
        ".statusbar #status\\.host .codicon": "margin: 0 auto;",
    }
}
```

Without the custom CSS settings, the activity bar looks as follows, which I am sure you'll agree, is far from ideal :)

<img width="370" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/ac598230-33de-4992-9516-71ef228bb9d9">

**Comment by andreiborisov** [comment]
@lehni, thank you for sharing your settings, my VS Code is beautiful again! Maybe maintaining those in a separate repo would make sense (as a custom setup of some sort for this extension)?

**Comment by drcika** [comment]
If I understood correctly
essentially you want to separate the width of the activity bar from the width of the items/icons(two separate configs). it can be done(after vacation :D)

padding-top let's say it's a bug.

extension does not hide host button (if it hides it is definitely a bug and I need a way to reproduce)

**Comment by lehni** [comment]
@drcika yes I suppose that could work, if setting the items width to 48px would result in them being positioned the same way as VSCode does it by default (height 48px, no extra vertical padding).

`margin: 0 auto` is still needed to make them center horizontally, it could be set by default.

But this also needs the `margin-top: var(--titlebar-height)` setting to make room for the traffic lights, which could perhaps be handled by APC.

**Comment by lehni** [comment]
Oh and you're right, the hosts button being hidden is not caused by APC, apologies for that mix-up.

**Comment by drcika** [comment]
@lehni 
ok now?
![Screenshot 2023-07-30 at 16 47 16](https://github.com/drcika/apc-extension/assets/35919606/a4259388-18e3-46a2-87a2-ee38ed603420)

**Comment by lehni** [comment]
@drcika better, thanks!

But I still need to reset the action items styling in the activity bar:

Left: Cleared (same as default VSCode)
Right: Uncleared (With APC Styling)

<img width="83" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/44ab6c26-fe77-4012-ad62-4c46ec3461ba"> <img width="84" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/27b567ed-beb1-4d11-92bc-eec0ae3409e7">

The problems:

* Not all icons appear at the same scale. This is caused by APC setting `-webkit-mask-size`. I can fix this by overriding it to `-webkit-mask-size: 1em`. This setting might actually work for all of APCs use-cases.
* The badges are in the wrong place
* The vertical paddings are too low

The settings I'm still using:

```jsonc
".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item": "margin-top: 0 !important;",
".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item a.action-label": "height: 48px; font-size: 24px; -webkit-mask-size: 1em;",
".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item .badge div.badge-content": "top: 24px; right: 8px;",
```

**Comment by lehni** [comment]
In addition to these tweaks, I also still need to set this:

```jsonc
// Don't indent the sidebar title.
".custom-sidebar-titlebar .sidebar .composite.title": "padding-left: 0;",
// Don't indent the statusbar items.
".monaco-workbench .part.statusbar>.items-container>.statusbar-item.left.first-visible-item": "padding-left: 0;",
```

**Comment by andreiborisov** [comment]
> In addition to these tweaks, I also still need to set this:
> 
> ```js
> // Don't indent the sidebar title.
> ".custom-sidebar-titlebar .sidebar .composite.title": "padding-left: 0;",
> // Don't indent the statusbar items.
> ".monaco-workbench .part.statusbar>.items-container>.statusbar-item.left.first-visible-item": "padding-left: 0;",
> ```

I'm curious about those, as it actually makes stuff unaligned compared to default settings.

**Comment by lehni** [comment]
hmmm, I don't think it does?

My first screenshot is the result of those settings applied. The second screenshot is without them.

In comparison, here how they look by default in VSCode:

<img width="53" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/0ad7e8cb-2bb9-46fc-bfcd-6bb418fbdd93">

**Comment by lehni** [comment]
A question of taste I guess. 

<img width="188" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/f6178e82-5299-4ed5-ba95-caef22549627">

**Comment by lehni** [comment]
That's a question of taste, I guess. Here's how those look. It feels well balanced to me.

<img width="339" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/1b784486-4dbf-4d76-92b3-dabeae863743">

**Comment by andreiborisov** [comment]
@lehni I have a different issue with your setup (and it was the same during Customize UI era): every time I reopen a VS Code window, it shrinks file explorer:

Before closing VS Code/its window:
<img width="1248" alt="CleanShot 2023-07-31 at 14 04 35@2x" src="https://github.com/drcika/apc-extension/assets/13354491/74e73758-785e-43ef-87f6-30eadf8204c8">

After closing VS Code/its window:
<img width="1227" alt="CleanShot 2023-07-31 at 14 05 04@2x" src="https://github.com/drcika/apc-extension/assets/13354491/0b295a06-ca5a-409c-8134-615fec834d9d">

It's quite annoying since, after a couple of iterations, it makes the file explorer tiny.

If it's something fixable in APC extension, I'll open another issue.

**Comment by lehni** [comment]
@andreiborisov I never noticed this, mainly because I have VSCode always open, but now that you're mentioning it, I am actually seeing it too.

And what's intersting is the math:

```
418 - 389 = 29
77 - 29 = 48
```
48: The default activity-bar width
77: The new activity-bar width, so that it fits the traffic lights 

I think VSCode has `- 48` hard-coded somewhere internally, where it calculates the explorer size to restore in the next session.

**Comment by drcika** [comment]
> @andreiborisov I never noticed this, mainly because I have VSCode always open, but now that you're mentioning it, I am actually seeing it too.
> 
> And what's intersting is the math:
> 
> ```
> 418 - 389 = 29
> 77 - 29 = 48
> ```
> 
> 48: The default activity-bar width 77: The new activity-bar width, so that it fits the traffic lights
> 
> I think VSCode has `- 48` hard-coded somewhere internally, where it calculates the explorer size to restore in the next session.

unfortunately, in many, many places they have a hard-coded values :( 

I don't have much time to deal with this extension, I've been doing this for my own needs, 
and it would mean a lot if any of you could contribute

**Comment by lehni** [comment]
@drcika the real bug in https://github.com/drcika/apc-extension/issues/52#issuecomment-1657230992 is that the icons aren't all appearing with the same scale factor when using a item size that is different from the activity bar size, due to `-webkit-mask-size` begin set to this calculation:

```css
-webkit-mask-size: calc(var(--activity-bar-action-item-size) * 0.8) calc(var(--activity-bar-action-item-size) * 0.8);
```

To compare, here with the `a.action-label { -webkit-mask-size: 1em; }` override, and without it. Compare the size of project manager (the folder), docker (the whale), live share (the rounded arrow), github actions (the bottom one). It looks like most of the action icons provided by extensions get bigger than they're supposed to with this setting, due to the mask being set in this way.

<img width="77" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/4abc1217-cc0d-446f-866c-7fe18df9aa6d"><img width="77" alt="image" src="https://github.com/drcika/apc-extension/assets/213275/99f17866-6362-4cd0-a142-a9874937b99e">



Setting it to `-webkit-mask-size: 1em;` is the right approach I believe. This is a low-hanging fruit that would already improve the behavior of the new `itemSize` setting.

But I also think that there should be a value I can set `itemSize` to, at which the activity bar looks "native", meaning it has the size size as by default, and also the same margins. Right now, everything gets way more condensed with smaller vertical margins and paddings, and the badges are in different places, leaving me no other choice than overriding everything with very specific CSS settings.

**Comment by lehni** [comment]
I've looked ai bit more into this now. So I'd want to be able to set `itemSize` to 48 to get the default VSCode look, which comes with 48px size. For this to work, what needs changing in the APC CSS settings is actually rather simple (ignoring the complex selectors needed to make them stick, I just show the actual HTML element selectors that they need to be applied to):

```css
li.action-item {
  margin-top: 0; /* instead of 3px, as hard-coded by APC */
}

a.action-label {
  font-size: calc(var(--activity-bar-action-item-size) * 0.5); /* instead of * 0.6, as hard-coded by APC */
  -webkit-mask-size: 1em; /* to fix the problem outlined above */
}
```

The batches actually use the correct calculations for the default look already.

And here the corresponding settings in the JSON:

```jsonc
"apc.stylesheet": {
    // Reset APC .activitybar styling back to VSCode defaults.
    ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item": "margin-top: 0 !important;",
    ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item a.action-label": "font-size: calc(var(--activity-bar-action-item-size) * 0.5); -webkit-mask-size: 1em;",
}
```

**Comment by drcika** [comment]
> I've looked ai bit more into this now. So I'd want to be able to set `itemSize` to 48 to get the default VSCode look, which comes with 48px size. For this to work, what needs changing in the APC CSS settings is actually rather simple (ignoring the complex selectors needed to make them stick, I just show the actual HTML element selectors that they need to be applied to):
> 
> ```css
> li.action-item {
>   margin-top: 0; /* instead of 3px, as hard-coded by APC */
> }
> 
> a.action-label {
>   font-size: calc(var(--activity-bar-action-item-size) * 0.5); /* instead of * 0.6, as hard-coded by APC */
>   -webkit-mask-size: 1em; /* to fix the problem outlined above */
> }
> ```
> 
> The batches actually use the correct calculations for the default look already.
> 
> And here the corresponding settings in the JSON:
> 
> ```js
> "apc.stylesheet": {
>     // Reset APC .activitybar styling back to VSCode defaults.
>     ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item": "margin-top: 0 !important;",
>     ".custom-activitybar div.monaco-workbench div.activitybar > div.content div.monaco-action-bar ul.actions-container li.action-item a.action-label": "font-size: calc(var(--activity-bar-action-item-size) * 0.5); -webkit-mask-size: 1em;",
> }
> ```

unfortunately I don't have time to work on the extension right now, I would be very grateful if you could do a PR

**Comment by lehni** [comment]
@drcika wow that was fast, thank you for merging both PRs so quickly! A new release with these two features in would be lovely! ;-)

**Comment by lehni** [comment]
Closing this since all required PRs were merged. @andreiborisov could you create a separate issue for this? https://github.com/drcika/apc-extension/issues/52#issuecomment-1658070320

**Comment by lehni** [comment]
With v0.2.9 released, my settings above can now be simplified to this:

```json
{
  "window.titleBarStyle": "native",
  "window.customTitleBarVisibility": "never",
  "window.density.editorTabHeight": "compact",
  "apc.electron": {
    "titleBarStyle": "hiddenInset",
  },
  "apc.header": {
    "height": 37
  },
  "apc.sidebar.titlebar": {
    "height": 37
  },
  "apc.activityBar": {
    "size": 77,
    "itemSize": 48,
    "itemMargin": 0
  }
}
```
