### ISSUE TITLE
VIbrancy on macOS with native tabs breaks left panel title

### ISSUE THREAD

**Issue by andynameistaken** [drcika/apc-extension#58]
It renders on top of buttons
![image](https://github.com/drcika/apc-extension/assets/15692002/ce8a2e09-241b-4fb3-b2bc-68d76710d3f5)

**Comment by bushaev-denis** [comment]
You can edit [my config](https://github.com/drcika/apc-extension/issues/5#issuecomment-1654267807).

**Comment by andynameistaken** [comment]
@dez64ru I couldn't make your solution to work with window tabs

**Comment by drcika** [comment]
should be fixed with v0.3.0
