### ISSUE TITLE
apc.imports doesnt work on mac

### ISSUE THREAD

**Issue by ctf0** [drcika/apc-extension#59]
i tried both
```json
"apc.imports": [
        "/Users/path/styles.css",
        // ...
    ],
```
and
```json
"apc.imports": [
        "file:///Users/path/styles.css",
        // ...
    ],
```

and non of the styles is applied to the editor.

```
Version: 1.82.0-insider
Commit: bf9c8105647b1e9d244f0f00155c21298e7554cf
Date: 2023-08-09T05:48:26.386Z
Electron: 25.4.0
ElectronBuildId: 22901934
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by drcika** [comment]
works, check your styles

![Screenshot 2023-08-13 at 15 46 08](https://github.com/drcika/apc-extension/assets/35919606/def792fe-6012-4cb0-8636-9663c255d6b3)
![Screenshot 2023-08-13 at 15 45 15](https://github.com/drcika/apc-extension/assets/35919606/47bea4ea-7d30-414a-92b7-0a64c6e1b993)
