### ISSUE TITLE
Is it possible to have transparent sidebar only

### ISSUE THREAD

**Issue by jeffreyvr** [drcika/apc-extension#62]
Hi,

I don't have an issue, but more a question. Is it possible to only make the sidebar have a slight transparency?

MacOs apps like Mail do this, and I would find it pretty neat if I can replicate that effect with vs code.

Nice work on the extension!

**Comment by drcika** [comment]
![Screenshot 2023-08-11 at 19 59 24](https://github.com/drcika/apc-extension/assets/35919606/f01d2c84-a641-477a-9ca5-46f136f4ed59)
![Screenshot 2023-08-11 at 20 02 26](https://github.com/drcika/apc-extension/assets/35919606/9e45dd5e-dc82-41f6-bfbc-8d389d02bb5d)

**Comment by jeffreyvr** [comment]
Very cool, thanks for sharing! :-)

<img width="1783" alt="Screenshot 2023-08-12 at 15 26 25" src="https://github.com/drcika/apc-extension/assets/9550079/a7401b77-1e1f-4aa3-b1d8-2f3c5b57be18">

**Comment by yang4515** [comment]
@jeffreyvr cool! Could you share your configuration?

**Comment by jeffreyvr** [comment]
@yang4515 Here are the relevant parts https://gist.github.com/jeffreyvr/3f931604d1b6b167494f6f47fb1aea86
