### ISSUE TITLE
List Row setting breaks some dropdowns

### ISSUE THREAD

**Issue by forivall** [drcika/apc-extension#63]
Steps to reproduce:

Enable `"apc.listRow"` with `height` and `fontSize`

Open a dropdown for icons in the settings editor - I search for "terminal default icon":
<img width="1016" alt="Screenshot 2023-08-11 at 11 56 47 AM" src="https://github.com/drcika/apc-extension/assets/760204/3d37ddbd-c440-4e35-b209-db95ae5a162a">
![Kapture 2023-08-11 at 11 54 33 resized](https://github.com/drcika/apc-extension/assets/760204/8e2ba313-1f2b-406a-ae50-47ece35b066f)

This is what the dropdown is supposed to look like, with `apc.listRow` off:

<img width="472" alt="Screenshot 2023-08-11 at 11 57 46 AM" src="https://github.com/drcika/apc-extension/assets/760204/f035aea4-aca7-442b-be86-78366992a0df">

**Comment by drcika** [comment]
should be fixed with v0.3.0
