### ISSUE TITLE
How hide or remove file header?

### ISSUE THREAD

**Issue by HeyProtagonist** [drcika/apc-extension#67]
I'm able to hide the elements in the tab bar. But I couldn't able to find the property hide or remove them!
---
![Screenshot](https://github.com/drcika/apc-extension/assets/75655740/cb86030e-62eb-41d6-935a-0590873bc448)

**Comment by drcika** [comment]
```
  "apc.header": {
    "height": 0.00001
  }
  ```

**Comment by HeyProtagonist** [comment]
Not working on my machine (Windows)..! May be we can't get rid of that workbench tabs panel ☹️

**Comment by HeyProtagonist** [comment]
Awesome Thanks... Is it possible to remove the container also..? 

I tried but it's kinda getting either laggy or crashing in some scenarios..!

**Comment by drcika** [comment]
I don't understand which container?

**Comment by HeyProtagonist** [comment]
okay, it's my fault 🙏. I should've stated the problem correctly. I'll close this issue and create the right in a bit.

Moved to 👉 #68
