### ISSUE TITLE
Hide Editor Groups Panel

### ISSUE THREAD

**Issue by HeyProtagonist** [drcika/apc-extension#68]
How to hide the editor groups bar and is there an API for it..?
---
![image](https://github.com/drcika/apc-extension/assets/75655740/cf5536fc-4d7d-49b2-b883-b016508afa6d)

**Comment by drcika** [comment]
the answer is the same
![Screenshot 2023-08-17 at 09 25 59](https://github.com/drcika/apc-extension/assets/35919606/7c100d6f-7b71-4a21-911d-807e8c785297)
![Screenshot 2023-08-17 at 09 25 40](https://github.com/drcika/apc-extension/assets/35919606/143f9a77-44ef-4a4c-85c1-082645260121)

**Comment by HeyProtagonist** [comment]
Not working for me..!

I commented on other changes and tried them. Any ideas?
---
![image](https://github.com/drcika/apc-extension/assets/75655740/4666ab16-af68-4999-aded-885a49d4e580)

**Comment by HeyProtagonist** [comment]
Figured 🙌

it's just the old configuration I had 👇

```JSON
"workbench.editor.showTabs": true, // Need to enable this in order make it hide again
```

Thanks for the help and patience mate 😅
