### ISSUE TITLE
customize iframe contents

### ISSUE THREAD

**Issue by lethefrost** [drcika/apc-extension#70]
Hi, thanks for creating this great extension! Since the update of VSC broke customize UI and monkey patch, it has been quite a hard and annoying time for me until I found this successor you made.

I am wondering whether it would be possible to also customize the contents in iframes? For example, in the extension marketplace, the readme files are presented and rendered as iframes. Some panes created by other extensions (like GitLens) also include embedded iframes.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension#apciframestyle

**Comment by lethefrost** [comment]
> https://github.com/drcika/apc-extension#apciframestyle

Sorry for the oversight and thanks for your help!
