### ISSUE TITLE
Stops working on 1.82

### ISSUE THREAD

**Issue by natew** [drcika/apc-extension#77]
Woke up this morning to a titlebar and sadness, just wanted to give a heads up it seems not to work with the latest VSCode.

**Comment by drcika** [comment]
try re-enabling the extension
https://github.com/drcika/apc-extension#enabling-and-disabling

**Comment by baccci** [comment]
Same here ✋ disabling and then enabling didn't work

**Comment by drcika** [comment]
more details needed, just checked everything works 
win/mac vscode, vscode insiders, vscodium

**Comment by baccci** [comment]
mac vscode, just checked disabling/enablig again and this time it worked 🙃

**Comment by natew** [comment]
Ah yea this worked, thanks man. Maybe in the future it could prompt you if your setting is enabled but its not enabled, I was trying reinstalling it and reloading VSCode, had no idea there's just a command.

**Comment by drcika** [comment]
there is a check 
vs code team strongly opposes extensions of this type and does everything to disable them
don't you remember they killed [customize-ui](https://github.com/iocave/customize-ui)

**Comment by diocletiann** [comment]
Re-enabling solved it in VSCodium. Thanks for doing the good work here.
