### ISSUE TITLE
Can I change the font family of the UI?

### ISSUE THREAD

**Issue by rafidoth** [drcika/apc-extension#8]
this extension is awesome. 

Is that possible to manipulate the css of the body using it? I tried this with the first apc.stylesheet option but its not working.
```
"apc.stylesheet": {
    "body": {
      // other panels should be transparent see "workbench.colorCustomizations"
      "background-image": "url(/Users/aleksandarpopovic/imgs/19.png), linear-gradient(to top,rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.2))",
      "background-size": "cover",
      "background-blend-mode": "multiply",
      "background-repeat": "no-repeat"
    }

  },
```

**Comment by drcika** [comment]
- you must have the desired font installed 
- vscode provide you some settings
![Screenshot 2023-06-04 at 09 57 28](https://github.com/drcika/apc-extension/assets/35919606/d6f7bded-88f8-4fbf-81b9-8377eecd6348)
- you must write an appropriate selector (https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) or use !important

**Comment by rafidoth** [comment]
Your mentioned CSS properties are working only. I wanted to modify other than those. 

![image](https://github.com/drcika/apc-extension/assets/67283985/91dd82a8-fb5a-4639-8dc4-dc5212f49630)

**Comment by drcika** [comment]
- Open developer toll
- Find element
![Screenshot 2023-06-05 at 05 28 49](https://github.com/drcika/apc-extension/assets/35919606/298b55e1-28ad-4d8a-917c-a6e080407f52)

- Copy first selector
![Screenshot 2023-06-05 at 05 31 08](https://github.com/drcika/apc-extension/assets/35919606/5282780f-2776-4ccf-828d-035b017f28c0)

- add style
![Screenshot 2023-06-05 at 05 32 06](https://github.com/drcika/apc-extension/assets/35919606/6a4f37ee-ddf0-4b1c-831b-ed54511e237c)
