### ISSUE TITLE
Broken in VS Code 1.82.x

### ISSUE THREAD

**Issue by fungilation** [drcika/apc-extension#80]
Looks like none of apc's styling is working since my VS Code upgrade to 1.82.1 on Mac.

My settings.json for reference:

```json
  "apc.activityBar": {
    "position": "bottom",
    "hideSettings": true,
    "size": 38
  },
  "apc.statusBar": {
    "position": "editor-bottom",
    "height": 22,
    "fontSize": 12
  },
  "apc.listRow": {
    "height": 21,
    "fontSize": 13
  },
  "apc.stylesheet" : {
    ".monaco-workbench .part.editor>.content .editor-group-container>.title div.tabs-container" : {
      "font-size": "12px"
    }
  },
```

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension/issues/77

**Comment by fungilation** [comment]
disable and re-enable in extensions pane does not work. But this does, from readme:

> Go to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
> Type "Enable Apc extension" to enable or "Disable Apc extension" to disable the extension.

**Comment by fungilation** [comment]
disable and re-enable in extensions pane does not work. But this does, from readme:

> Go to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
> Type "Enable Apc extension" to enable
