### ISSUE TITLE
Can I set tabs to statusBar

### ISSUE THREAD

**Issue by KiligFei** [drcika/apc-extension#82]
I want to set tabs to statusBar or put them at the bottom. Could you help me? Thank you.
I wanted to focus more on writing and looking at code, but at the same time I had the need to switch between different tabs, so this weird idea came up

**Comment by webuniverseio** [comment]
This is not a weird idea, it is fairly practical, however probably it is not possible to do with vscode at the moment :( 
https://github.com/microsoft/vscode/issues/140674
