### ISSUE TITLE
How to set background opacity only

### ISSUE THREAD

**Issue by yang4515** [drcika/apc-extension#83]
Is it possible to set only the background opacity? Setting the overall opacity makes the code unclear.

**Comment by amnweb** [comment]
I believe that is not possible, Don't know why is not included setBackgroundMaterial options for electron so we can set acrylic background for windows

**Comment by drcika** [comment]
> I believe that is not possible, Don't know why is not included setBackgroundMaterial options for electron so we can set acrylic background for windows

All electron options are supported https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions
```
  "apc.electron": {
    "backgroundMaterial": "acrylic"
  },
 ```

**Comment by amnweb** [comment]
So "backgroundMaterial": "acrylic" is working only with "window.titleBarStyle": "native", and does not work in editor ?

**Comment by drcika** [comment]
"backgroundMaterial string (optional) Windows - Set the window's system-drawn background material, including behind the non-client area. Can be auto, none, mica, acrylic or tabbed. 
Note: This method is only supported on Windows 11 22H2 and up."

**Comment by amnweb** [comment]
Ok but I still don't understand why it doesn't work acrylic or tabbed in editor, simple backgroundMaterial does not have any effect even if is enabled

**Comment by drcika** [comment]
Other panels must be transparent to use the `vibrancy` option
[Demo](https://github.com/drcika/apc-extension/blob/production/demo/vibrancy.settings.json)

**Comment by amnweb** [comment]
Shouldn't vibrancy only work on macos ? I talk about windows 11 if i set all panel to transparent i have black screen only.
