### ISSUE TITLE
vscode 1.82.2 doesn't work

### ISSUE THREAD

**Issue by bisho** [drcika/apc-extension#84]
My vscode updated automatically and the latest version doesn't seem to be supported in the extension. No aparent errors, but no customizations. If you need any help to debug or additional info, let me know.

**Comment by amnweb** [comment]
Try to restart/reenable extension, for me it's working fine on 1.82.2

**Comment by bisho** [comment]
My bad, disable and re-enable did work. Thanks!

**Comment by crispinkoech** [comment]
Doesn't seem to work for me anymore, disabling and re-enabling doesn't fix the issue :(

I'm on version 1.83.0, on mac M1

**Comment by drcika** [comment]
is working...
![Screenshot 2023-10-05 at 10 36 49](https://github.com/drcika/apc-extension/assets/35919606/973e0a84-1087-41e7-8094-b05280e664f1)

**Comment by crispinkoech** [comment]
Ahh, found this comment on another thread; basically disabling/enabling via extensions page doesn't work.

https://github.com/drcika/apc-extension/issues/80#issuecomment-1718161121

Thanks! 👍

**Comment by chriszrc** [comment]
@crispinkoech thank you! only doing through the command palette worked-

> Go to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
> Type "Enable Apc extension" to enable
