### ISSUE TITLE
Center the terminal panel like a floating div #152

### ISSUE THREAD

**Issue by EliTheSurfer** [drcika/apc-extension#87]
Hello everybody,
Is it possible to center the panel like a floating div with customise-ui ? I've put an image as an example of the final result that I'm trying to achieve.
I'd truly appreciate if someone can help me on this.
![image](https://user-images.githubusercontent.com/19303337/195468829-80a90ef4-c745-4528-a0cc-527dc9c97ce8.png)

**Comment by drcika** [comment]
it is possible, there is a lot of work, there will be a lot of side effects,
maybe I'll work on it sometime when I have time
this should be a request for the vscode team
