### ISSUE TITLE
Lag when transparent is on

### ISSUE THREAD

**Issue by tobedecided0601** [drcika/apc-extension#88]
I notice when the transparent is enabled, the window would lag massively (dragging around, open up Mission Control, etc.). While using [illixion/vscode-vibrancy-continued](https://github.com/illixion/vscode-vibrancy-continued), the lag is literally non-existent.

If there a way to set the update interval similar to that one, it'd be nice.

OS: macOS 14
VSCode: 1.82.2

https://github.com/drcika/apc-extension/assets/34794115/06a98a46-8eed-4779-973f-9a40064cd5ed

Video is 60fps, the desktop isn't during Mission Control.

**Comment by drcika** [comment]
Unfortunately, I can do nothing more than passing the configuration to the electron

**Comment by tobedecided0601** [comment]
ah that's very unfortunate then

**Comment by tobedecided0601** [comment]
It seems that I need to remove `transparency` and only use `vibrancy`. I don't know how it worked but it fixed the problem!

Since `transparency` is not enabled, I also get the window's shadow back!
