### ISSUE TITLE
Not working with the latest VS Code

### ISSUE THREAD

**Issue by jahirfiquitiva** [drcika/apc-extension#90]
Version info
![Shot 2023-10-12 at 10 14 52@2x](https://github.com/drcika/apc-extension/assets/10360816/3321c552-5879-47ba-8109-c331675666c0)

**Comment by backermanbd** [comment]
The extension works flawlessly.

Can you share your apc-extension settings here? Only version info won't solve the problem.
If you still haven't configured the settings, I suggest you do so.

**Comment by drcika** [comment]
#80

**Comment by drcika** [comment]
#80 
> Go to the Command Palette by pressing Cmd+Shift+P on Mac or Ctrl+Shift+P on Windows.
> Type "Enable Apc extension" to enable

**Comment by jahirfiquitiva** [comment]
Running the command from the Command Palette worked, thanks!

**Comment by lkuoch** [comment]
I'm on the latest code-insiders running on mac m1 and the apc settings are not working

<img width="297" alt="image" src="https://github.com/drcika/apc-extension/assets/36609992/1839d542-cdf6-4932-97de-7f7ed16ec0b8">

**Comment by backermanbd** [comment]
Checked yesterday. Still runs perfectly on mac m1

**Comment by nx-alejandrolacasa** [comment]
Same issue in current stable version:

<img width="243" alt="image" src="https://github.com/drcika/apc-extension/assets/15908038/bf393597-5045-4612-a93f-148fd52c42bd">
<br />
I've run the "Enable Apc extension" and still not working... :(

**Comment by julesjacobs** [comment]
I have the same issue, making the editor tabs appear on the very top no longer works.
