### ISSUE TITLE
Just a heads-up, moving activity bar to the top of side bar in VSCode Insider

### ISSUE THREAD

**Issue by ghost** [drcika/apc-extension#92]
This might not impact the apc-extension, but I wanted to update you. 

This feature is in vscode Insider and will come in the next release (v1.84) of vscode. 

Check out the tweet: https://x.com/sandy081/status/1714566984170361018?s=20.

**Comment by drcika** [comment]
they are finally doing their job :D
that part of the extension will be deprecated

**Comment by ghost** [comment]
Yes, it does seem that way. But I'm not sure if they'll include the down position as well.

**Comment by ghost** [comment]
Released https://code.visualstudio.com/updates/v1_84#_workbench

**Comment by ghost** [comment]
@drcika Will you deprecate the `top` setting or include this in the readme?

Here's the vscode default.
```
{
    "workbench.activityBar.location": "top",
}
```

**Comment by jdalrymple** [comment]
> Yes, it does seem that way. But I'm not sure if they'll include the down position as well.

It looks like they didnt...

**Comment by ghost** [comment]
Sad as always.
