### ISSUE TITLE
How do I display workspace name in the sidebar title?

### ISSUE THREAD

**Issue by o-nazaruk** [drcika/apc-extension#93]
Hello!

I really like this extension, because it helps me save precious screen space on a smaller laptop. My setup has been configured like so:

```jsonc
  "window.titleBarStyle": "native",
  "apc.electron": {
    "titleBarStyle": "customButtonsOnHover",
    "frame": false,
    "trafficLightPosition": {
      "x": -12,
      "y": -12
    }
  },
  "apc.header": {
    "height": 37
  },
  "apc.sidebar.titlebar": {
    "height": 37
  },
<img width="1800" alt="Screenshot 2023-10-21 at 13 59 42" src="https://github.com/drcika/apc-extension/assets/13257217/edc81e6b-706c-4aa7-82e0-57ea029bd1de">

  "apc.activityBar": {
    "size": 77,
    "itemSize": 48,
    "itemMargin": 0
  },
  "apc.stylesheet": {
    // Don't indent the sidebar title.
    ".custom-sidebar-titlebar .sidebar .composite.title": "padding-left: 0;",
    // Don't indent the statusbar items.
    ".monaco-workbench .part.statusbar>.items-container>.statusbar-item.left.first-visible-item": "padding-left: 0;",
    // Show the host button, and make it as wide as the .activitybar.
    ".statusbar #status\\.host .codicon": "margin: 0 auto;",
    ".inline-tabs-placeholder": "display: none;",
    ".editor-actions": "display: none;"
  },
```

What I want to do is have a workspace name in the sidebar title, so that I can have a quick and easy way to tell which project is open. Here's what I imagine it should look like:
<img width="1800" alt="Screenshot 2023-10-21 at 13 59 42" src="https://github.com/drcika/apc-extension/assets/13257217/5c7ad866-9435-44cb-a853-b2a6f55f052b">

I would appreciate any help on this! Thank you

**Comment by drcika** [comment]
only like this

![Screenshot 2023-10-21 at 18 05 54](https://github.com/drcika/apc-extension/assets/35919606/965e7f07-678b-4aa8-9d8a-7a3e38e245e4)

**Comment by o-nazaruk** [comment]
Thank you for your reply!

How can I set this up?

**Comment by drcika** [comment]
deselect all
