### ISSUE TITLE
On Mac, hidden activity bar causes traffic light overlap in inline title bar

### ISSUE THREAD

**Issue by ghost** [drcika/apc-extension#94]
```
    "apc.electron": {
      "titleBarStyle": "hidden",
    },
    "window.titleBarStyle": "native",
    "workbench.activityBar.visible": false,
```

<img width="825" alt="Screenshot 2023-10-22 at 9 09 10 PM" src="https://github.com/drcika/apc-extension/assets/84121715/66e24c17-d890-4993-8bf5-76ce4f342683">

**Comment by ghost** [comment]
@drcika Could you look into this problem?

**Comment by h-jia** [comment]
use "`hiddenInset`" instead of "`hidden`"

**Comment by heyman** [comment]
~~An alternative (that might be of interest to some) is to hide the traffic lights completely which can be done by setting `trafficLightPosition` to a negative value.~~

EDIT: Just found out about the `customButtonsOnHover` for `apc.electron.titleBarStyle` which is probably a better solution.

**Comment by xzbdmw** [comment]
hiddeninset don't work too.
Only when apc.activityBar is set to buttom or top, traffic light won't overlay with titiles.
<img width="983" alt="image" src="https://github.com/drcika/apc-extension/assets/97848247/9bc163c6-40ef-4288-951e-af50675a15c9">

**Comment by CassandraCat** [comment]
I encountered the same issue. How to solve it?
