### ISSUE TITLE
Any idea how to get rid of the active editor bottom line

### ISSUE THREAD

**Issue by vivianludrick** [drcika/apc-extension#95]
Any idea how to get rid of the white line
![image](https://github.com/drcika/apc-extension/assets/116781909/8e561ffd-9f3c-42b3-be27-73996bcafcc1)

**Comment by vivianludrick** [comment]
```json 
 "workbench.colorCustomizations":{
    "tab.activeBorder": "#0000",
}
```
took a while to find but here's the solution

**Comment by darianmorat** [comment]
I want to be able to see the tab border at the top when using the apc. But it looks that removes that completely, I can just see it when I am full screen... any idea? 

![Screenshot 2024-01-18 165006](https://github.com/drcika/apc-extension/assets/80854633/e7d4aac1-b604-4837-a709-3547132c877b)

![Screenshot 2024-01-18 165014](https://github.com/drcika/apc-extension/assets/80854633/0f6309db-3d33-4a75-80e9-b87839e27500)
