### ISSUE TITLE
[Windows] Elevation not always required

### ISSUE THREAD

**Issue by RivenSkaye** [drcika/apc-extension#96]
With single-user installs (install as normal user, "only for me" option) there's no requirement for administrator rights. I wager any portable install on an rwx-mounted drive would work on UNIX-like operating systems without elevation as well, but I don't have the means to test that atm.

This was a pleasant surprise for me considering the readme lists it as a requirement

**Comment by ghost** [comment]
I agree. Tested (yesterday) on both Mac and Windows. Permission is not needed.

If VSCode starts acting weird with the extension, you might have to permit it to play nice.

Check out the updated docs here: https://github.com/drcika/apc-extension#readme

**Comment by ghost** [comment]
> This was a pleasant surprise for me, considering the readme lists it as a requirement

@RivenSkaye It's not a requirement anymore.

For Linux, I think it's a must. There's no alternative other than to claim ownership of the installation directory.
Here's a similar issue regarding this: https://github.com/drcika/apc-extension/issues/49#issuecomment-1646332813
